// Units File

"DOTAUnits"
{
	"Version"	"1"
	
// Wave undyings

	"npc_undying"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undyindg.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_1"
		"Ability2"					""
		"Ability3"					"blood_effect"	
		"Ability4"					"attack_of_deactivating"
		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"15"
		"MagicalResistance"         "45"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"140"
		"AttackDamageMax"			"170"
		"AttackRate"				"1.15"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"150"
		"BountyGoldMin"				"100"	
		"BountyGoldMax"				"120"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"950"
		"StatusHealthRegen"			"15"
		"StatusMana"				"350"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "392" }
					"Wearable1" { "ItemDef" "393" }
					"Wearable1" { "ItemDef" "542" }
					"Wearable1" { "ItemDef" "616" }
 
 				
				}
    	"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"tombestone_und_1"										
				}
				
			}		
			
		}
	}
	

	"npc_undying_2"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undyindg.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_2"
		"Ability2"					""
		"Ability3"					"blood_effect"	
		"Ability4"					"attack_of_deactivating"
		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"30"
		"MagicalResistance"         "65"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"370"
		"AttackDamageMax"			"430"
		"AttackRate"				"1.1"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"260"
		"BountyGoldMin"				"200"	
		"BountyGoldMax"				"230"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1750"
		"StatusHealthRegen"			"20"
		"StatusMana"				"350"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "13484" }
					"Wearable1" { "ItemDef" "13483" }
					"Wearable1" { "ItemDef" "542" }  
					"Wearable1" { "ItemDef" "13482" }
 
 				
				}
    	"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"tombestone_und_2"										
				}
				
			}		
			
		}
	}
	

	"npc_undying_3"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undyindg.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_3"
		"Ability2"					"ghoul_crazy_look"
		"Ability3"					"blood_effect"	
		"Ability4"					"attack_of_deactivating"
		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"50"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"540"
		"AttackDamageMax"			"650"
		"AttackRate"				"0.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"460"
		"BountyGoldMin"				"420"	
		"BountyGoldMax"				"450"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2750"
		"StatusHealthRegen"			"22"
		"StatusMana"				"350"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9913" }
					"Wearable1" { "ItemDef" "9910" }
					"Wearable1" { "ItemDef" "542" }  
					"Wearable1" { "ItemDef" "7938" }
 
 				
				}
    	"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"tombestone_und_3"										
				}
				
			}		
			
		}
	}
	
	"npc_undying_4"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undyindg.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_4"
		"Ability2"					"ghoul_crazy_look"
		"Ability3"					"blood_effect"	
		"Ability4"					"attack_of_deactivating"
		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"55"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"840"
		"AttackDamageMax"			"1050"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"860"
		"BountyGoldMin"				"620"	
		"BountyGoldMax"				"850"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4350"
		"StatusHealthRegen"			"22"
		"StatusMana"				"350"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "12499" }
					"Wearable1" { "ItemDef" "12497" }
					"Wearable1" { "ItemDef" "542" }  
					"Wearable1" { "ItemDef" "7938" }
 
 				
				}
    	"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"tombestone_und_4"										
				}
				
			}		
			
		}
	}
	
	
	"npc_zombie_toxic"	
	{
 
 		"vscripts"		"ai/ai_toxic.lua"      
		"Model"						"models/heroes/undying/undying_flesh_golem_rubick.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".5"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"spider_explode_lua"
		"Ability2"					"attack_of_deactivating"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"10"
		"MagicalResistance"         "20"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"60"
		"AttackDamageMax"			"60"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"20"
		"BountyGoldMin"				"5"	
		"BountyGoldMax"				"15"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"200"
		"StatusHealthRegen"			"5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
									"EquippedItems"
			{
				"1"            	{"Item"        "item_toxic_boots"}
 

			}
		}
	}
	
	
	"npc_zombie_toxic_2"	
	{
 
 		"vscripts"		"ai/ai_toxic.lua"      
		"Model"						"models/heroes/undying/undying_flesh_golem_rubick.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".6"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"spider_explode_lua_2"
		"Ability2"					"attack_of_deactivating"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"17"
		"MagicalResistance"         "45"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"220"
		"AttackDamageMax"			"230"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"50"
		"BountyGoldMin"				"20"	
		"BountyGoldMax"				"30"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"350"
		"StatusHealthRegen"			"5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
									"EquippedItems"
			{
				"1"            	{"Item"        "item_toxic_boots"}
 

			}
		}
	}
	
	
	"npc_zombie_toxic_3"	
	{
 
 		"vscripts"		"ai/ai_toxic.lua"      
		"Model"						"models/heroes/undying/undying_flesh_golem_rubick.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".7"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"spider_explode_lua_3"
		"Ability2"					"attack_of_deactivating"
		"Ability3"					"ghoul_crazy_look"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"38"
		"MagicalResistance"         "70"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"360"
		"AttackDamageMax"			"380"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"160"
		"BountyGoldMin"				"60"	
		"BountyGoldMax"				"80"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"650"
		"StatusHealthRegen"			"5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
									"EquippedItems"
			{
				"1"            	{"Item"        "item_toxic_boots"}
 

			}
		}
	}
	
	
	"npc_zombie_toxic_4"	
	{
 
 		"vscripts"		"ai/ai_toxic.lua"      
		"Model"						"models/heroes/undying/undying_flesh_golem_rubick.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".8"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"spider_explode_lua_4"
		"Ability2"					"attack_of_deactivating"
		"Ability3"					"ghoul_crazy_look"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"43"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"425"
		"AttackDamageMax"			"525"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"420"
		"BountyGoldMin"				"120"	
		"BountyGoldMax"				"180"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1000"
		"StatusHealthRegen"			"5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
									"EquippedItems"
			{
				"1"            	{"Item"        "item_toxic_boots"}
 

			}
		}
	}
	

	"npc_flash_golem"	
	{
		// General
		//----------------------------------------------------------------
		
  		"vscripts"		"ai/ai_flash.lua"      
		"Model"						"models/items/undying/flesh_golem/davy_jones_set_davy_jones_set_kraken/davy_jones_set_davy_jones_set_kraken.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"10"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"
		"IsAncient"                 "1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"alchemist_acid_spray_flash_1"
		"Ability2"					"undying_soul_rip_flash_1"
		"Ability3"					"blood_effect"	
		"Ability4"                  "flash_dispersion"
		"Ability5"					"attack_of_deactivating"
		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"50"
		"MagicalResistance"         "70"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"530"
		"AttackDamageMax"			"570"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"115"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"1150"
		"BountyGoldMin"				"1"	
		"BountyGoldMax"				"2"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"3750"
		"StatusHealthRegen"			"15"
		"StatusMana"				"1050"	
		"StatusManaRegen"			"1.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
 			"DisableResistance"			"15.0"
			
    	"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"tombestone_und_1"										
				}
				
			}		
			
		}
	}

	"npc_flash_golem_2"	
	{
		// General
		//----------------------------------------------------------------
		
       		"vscripts"		"ai/ai_flash.lua"     
		"Model"						"models/items/undying/flesh_golem/ti8_undying_miner_flesh_golem/ti8_undying_miner_flesh_golem.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"10"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"
		"IsAncient"                 "1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"alchemist_acid_spray_flash_2"
		"Ability2"					"undying_soul_rip_flash_2"
		"Ability3"					"blood_effect"	
		"Ability4"                  "flash_dispersion"
		"Ability5"					"attack_of_deactivating"
		"Ability6"					"tombestone_flash_1"
		"Ability7"					"ghoul_crazy_look"
		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"60"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"885"
		"AttackDamageMax"			"985"
		"AttackRate"				"1.5"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"115"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"1850"
		"BountyGoldMin"				"1"	
		"BountyGoldMax"				"2"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"6650"
		"StatusHealthRegen"			"25"
		"StatusMana"				"1550"	
		"StatusManaRegen"			"1.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
			"DisableResistance"			"30.0"
			
    	"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"tombestone_und_1"										
				}
				
			}		
			
		}
	}	
	
	
	"npc_flash_golem_3"	
	{
		// General
		//----------------------------------------------------------------
		
       		"vscripts"		"ai/ai_flash.lua"     
		"Model"						"models/items/undying/flesh_golem/deathmatch_dominator_golem/deathmatch_dominator_golem.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"10"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"              "1"
		"IsAncient"                 "1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"alchemist_acid_spray_flash_3"
		"Ability2"					"undying_soul_rip_flash_3"
		"Ability3"					"blood_effect"	
		"Ability4"                  "flash_dispersion"
		"Ability5"					"attack_of_deactivating"
		"Ability6"					"tombestone_flash_2"
		"Ability7"					"ghoul_crazy_look"
		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"75"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1575"
		"AttackDamageMax"			"1888"
		"AttackRate"				"1.4"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"115"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"2350"
		"BountyGoldMin"				"1"	
		"BountyGoldMax"				"2"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"13350"
		"StatusHealthRegen"			"50"
		"StatusMana"				"2550"	
		"StatusManaRegen"			"1.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
		

			"DisableResistance"			"50.0"
			
						"EquippedItems"
			{
				"1"            	{"Item"        "item_abyssal_blade_flash"}
 

			}
			
		}
	}
	
// Boss

	"npc_boss_pig"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/ai_boss_pig.lua"		
		"Model"						"models/props_gameplay/pig.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"7"
		"ModelScale" 				"3"
		"UseNeutralCreepBehavior"	"0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"mars_bulwark"
		"Ability2"					"pig_open_wounds"
		"Ability3"					"slark_dark_pact"	
		"Ability4"					"blood_effect"
		"Ability5"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"15"
		"MagicalResistance"         "35"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"235"
		"AttackDamageMax"			"275"
		"AttackRate"				"1.3"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"825"
		"BountyGoldMin"				"100"	
		"BountyGoldMax"				"115"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"265"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1750"
		"StatusHealthRegen"			"5"
		"StatusMana"				"600"	
		"StatusManaRegen"			"3.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

 
	}
	
	"npc_boss_dead_pig"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/ai_boss_dead_pig.lua"		
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"15"
		"ModelScale" 				"2.5"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"              "1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"dead_stealer_feast"
		"Ability2"					"pig_dead_open_wounds"
		"Ability3"					"lifestealer_passive"	
		"Ability4"					"blood_effect"
		"Ability5"					"aghsfort_lifestealer_enraged_pulse"
		"Ability6"					"ghoul_crazy_look"
		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"52"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"895"
		"AttackDamageMax"			"1350"
		"AttackRate"				"1.15"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"5250"
		"BountyGoldMin"				"350"	
		"BountyGoldMax"				"750"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"12500"
		"StatusHealthRegen"			"35"
		"StatusMana"				"2500"	
		"StatusManaRegen"			"3.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"850"
		"VisionNighttimeRange"		"850"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9215" }
					"Wearable1" { "ItemDef" "13787" }
					"Wearable1" { "ItemDef" "12934" }
					"Wearable1" { "ItemDef" "6475" }
				}
				
		
 			"DisableResistance"			"80.0"
			
		"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance_dead_boss"}
				"2"            	{"Item"        "item_assault_dead_boss"}
 
			}
		}
		
	}


//Xuita

	"npc_classic_pig"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/props_gameplay/pig.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"blood_effect"
		"Ability2"					"respawn_strong"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"5"
		"MagicalResistance"         "10"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"10"
		"AttackDamageMax"			"20"
		"AttackRate"				"1.5"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"27"
		"BountyGoldMin"				"20"	
		"BountyGoldMax"				"25"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"170"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"120"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}

		"npc_timur"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/props_gameplay/chicken.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.5"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"100000"
		"BountyGoldMin"				"100000"	
		"BountyGoldMax"				"100000"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"0"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1"
		"StatusHealthRegen"			"1.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}

	"npc_classic_sheep"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/hex/sheep_hex/sheep_hex.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"blood_effect"
		"Ability2"					"respawn_strong"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"5"
		"MagicalResistance"         "10"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"10"
		"AttackDamageMax"			"20"
		"AttackRate"				"1.5"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"27"
		"BountyGoldMin"				"20"	
		"BountyGoldMax"				"25"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"220"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"120"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}
	
		"npc_classic_chicken"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/hex/fish_hex/fish_hex.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"3"
		"ModelScale" 				"1"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"blood_effect"
		"Ability2"					"respawn_fish"
		"Ability3"					"slark_pounce"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"17"
		"MagicalResistance"         "40"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"120"
		"AttackDamageMax"			"145"
		"AttackRate"				"1.4"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"45"
		"BountyGoldMin"				"55"	
		"BountyGoldMax"				"60"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"255"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"350"
		"StatusHealthRegen"			"2"
		"StatusMana"				"200"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
			"OffensiveAbilities"
			{
				"Ability3"
				{
					"Name"					"slark_pounce"										
				}
				
			}
			
 
		}
	}
	
			"npc_stronger_chicken"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/hex/fish_hex_retro/fish_hex_retro.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"4"
		"ModelScale" 				"1"
		"UseNeutralCreepBehavior"	"1"
		"HasInventory"				"1"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"blood_effect"
		"Ability2"					"respawn_fish"
		"Ability3"					"slark_pounce"	
		"Ability4"					""
		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"22"
		"MagicalResistance"         "40"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"155"
		"AttackDamageMax"			"175"
		"AttackRate"				"1"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"60"
		"BountyGoldMin"				"70"	
		"BountyGoldMax"				"80"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"575"
		"StatusHealthRegen"			"5"
		"StatusMana"				"350"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
						"OffensiveAbilities"
			{
				"Ability3"
				{
					"Name"					"slark_pounce"										
				}
				
			}
			
						"EquippedItems"
			{
				"1"            	{"Item"        "item_orb_of_venom"}
 

			}
		}
	}


	"npc_classic_half_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion_torso.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"blood_effect"
		"Ability2"					"attack_of_deactivating"
		"Ability3"					""	
		"Ability4"					"respawn_strong"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"10"
		"MagicalResistance"         "15"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"50"
		"AttackDamageMax"			"75"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"45"
		"BountyGoldMin"				"35"	
		"BountyGoldMax"				"45"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"170"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"150"
		"StatusHealthRegen"			"2"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}


	"npc_classic_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				"0.9"
		

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"blood_effect"
		"Ability2"					"attack_of_deactivating"
		"Ability3"					""	
		"Ability4"					"respawn_zombie_big"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"26"
		"MagicalResistance"         "45"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"165"
		"AttackDamageMax"			"200"
		"AttackRate"				"1.3"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"60"
		"BountyGoldMin"				"75"	
		"BountyGoldMax"				"85"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"220"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"750"
		"StatusHealthRegen"			"15"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}


	"npc_classic_wave_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"
        "BoundsHullName"         "DOTA_HULL_SIZE_SMALL"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"blood_effect"
		"Ability2"					"attack_of_deactivating"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"15"
		"MagicalResistance"         "35"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"72"
		"AttackDamageMax"			"75"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"20"
		"BountyGoldMin"				"3"	
		"BountyGoldMax"				"5"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"625"
		"StatusHealthRegen"			"5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}
	
	
	"npc_classic_skelet"	
	{
		// General
		//----------------------------------------------------------------
        "vscripts"        "ai/ai_skelet.lua"
		"Model"						"models/items/wraith_king/arcana/wk_arcana_skeleton.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"3"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior" 	"0"
		"HasInventory"				"1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"blood_effect"
		"Ability2"					"attack_of_deactivating"
		"Ability3"					"clinkz_wind_walk"	
		"Ability4"					"respawn_zombie_big"
		"Ability5"					"centaur_khan_endurance_aura"    
		"Ability6"					"ghoul_crazy_look"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"30"
		"MagicalResistance"         "50"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"195"
		"AttackDamageMax"			"225"
		"AttackRate"				"1.5"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"90"
		"BountyGoldMin"				"130"	
		"BountyGoldMax"				"140"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"325"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1250"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
									"EquippedItems"
			{
				"1"            	{"Item"        "item_blight_stone"}

			}
		}
	}

	
		"npc_classic_skeleton_king"	
	{
		// General
		//----------------------------------------------------------------
        "vscripts"        "ai/ai_skelet_king.lua"
		"UseNeutralCreepBehavior" 	"0"
		"Model"						"models/items/wraith_king/arcana/wraith_king_arcana.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_SkeletonKing"
		"GameSoundsFile"			"soundevents/game_sounds_skeletonking.vsndevts"
		"Level"						"4"
		"ModelScale" 				"1.5"
		"HasInventory"				"1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"blood_effect"
		"Ability2"					"attack_of_deactivating"
		"Ability3"					"skeleton_king_hellfire_blast"	
		"Ability4"					"respawn_zombie_big"
		"Ability5"					"spawnlord_aura"
		"Ability6"					"skeleton_king_mortal_strike"
		"Ability7"					"ghoul_crazy_look"
		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"36"
		"MagicalResistance"         "50"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"330"
		"AttackDamageMax"			"360"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"130"
		"BountyGoldMin"				"200"	
		"BountyGoldMax"				"220"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"335"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2250"
		"StatusHealthRegen"			"0"
		"StatusMana"				"750"	
		"StatusManaRegen"			"10.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DisableResistance"			"50.0"

			"DefaultState"			"Invade"
			"States"	
			{
				"Invade"
				{
					"Name"				"Invade"
					"Aggression"		"99.0" //cast offensive spells whenever
					"Avoidance"			"0.0" //dont flee
					"Support"			"66.0" //start buffing
				}
			}
						"AttachWearables"
				{
					"Wearable1" { "ItemDef" "13760" }
					"Wearable1" { "ItemDef" "13456" }
					"Wearable1" { "ItemDef" "13473" }
					"Wearable1" { "ItemDef" "13569" }
					"Wearable1" { "ItemDef" "13571" }
					"Wearable1" { "ItemDef" "13743" }
 				
				}
				
											"OffensiveAbilities"
			{
				"Ability3"
				{
					"Name"					"skeleton_king_hellfire_blast"										
				}
				
			}		
						"EquippedItems"
			{
				"1"            	{"Item"        "item_satanic"}
 				"2"            	{"Item"        "item_assault"}

			}
			
		}
	}
	

	"npc_classic_big_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"9"
		"ModelScale" 				"1.5"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"blood_effect"
		"Ability2"					"attack_of_deactivating"
		"Ability3"					"zombie_poison_sting_big"	
		"Ability4"					"respawn_zombie_big"    
		"Ability5"					"ghoul_crazy_look"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"36"
		"MagicalResistance"         "50"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"320"
		"AttackDamageMax"			"360"
		"AttackRate"				"1.4"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"80"
		"BountyGoldMin"				"115"	
		"BountyGoldMax"				"130"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1400"
		"StatusHealthRegen"			"20"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}
	
	"npc_classic_necr"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/necrolyte/necrolyte.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Necrolyte"
		"GameSoundsFile"			"soundevents/game_sounds_necrolyte.vsndevts"
		"Level"						"9"
		"ModelScale" 				"0.8"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"necrolyte_death_pulse"
		"Ability2"					"blood_effect"
		"Ability3"					"attack_of_deactivating"
		"Ability4"					"necrolyte_heartstopper_aura_2"	   
		"Ability5"					"respawn_zombie_big"
		"Ability6"					"ghoul_crazy_look"
 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"24"
		"MagicalResistance"         "60"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"120"
		"AttackDamageMax"			"140"
		"AttackRate"				"1.1"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"550"
		"ProjectileModel"			"particles/econ/items/necrolyte/necrophos_sullen_gold/necro_sullen_pulse_enemy_gold.vpcf"
		"ProjectileSpeed"			"600"			// Speed of projectile.		

	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"70"
		"BountyGoldMin"				"95"	
		"BountyGoldMax"				"110"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"170"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"925"
		"StatusHealthRegen"			"2.5"
		"StatusMana"				"800"	
		"StatusManaRegen"			"20.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "7427" }
					"Wearable1" { "ItemDef" "8043" }
					"Wearable1" { "ItemDef" "8044" }
					"Wearable1" { "ItemDef" "8045" }
 				
				}
				
							"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"necrolyte_death_pulse"										
				}
				
			}
		}
	}

	"npc_classic_wave_big_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.5"
        "BoundsHullName"         "DOTA_HULL_SIZE_SMALL"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"blood_effect"
		"Ability2"					"attack_of_deactivating"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"27"
		"MagicalResistance"         "50"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"145"
		"AttackDamageMax"			"155"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"30"
		"BountyGoldMin"				"8"	
		"BountyGoldMax"				"10"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1450"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}


	"npc_classic_pudge5"	
	{
		"vscripts"		"ai/ai_neutral_autocast.lua"
		"Model"						"models/heroes/pudge/pudge.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"5"
		"ModelScale" 				"2"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior" 	"0"
		"IsAncient"					"1"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"blood_effect"  
		"Ability3"					"pudge_meat_hook_2"	
		"Ability4"					"attack_of_deactivating"
		"Ability5"					"pudge_rot_passive"
		"Ability6"					"pudge_dismember_2"	
		"Ability7"					"respawn_zombie_big"	 
		"Ability8"					"hardskin_pudge"
 	 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"45"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"875"
		"AttackDamageMax"			"1100"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"700"
		"BountyGoldMin"				"870"	
		"BountyGoldMax"				"1200"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"325"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"5500"
		"StatusHealthRegen"			"50"
		"StatusMana"				"1250"	
		"StatusManaRegen"			"15.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"



		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
					"DisableResistance"			"70.0"
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "800.0"
			    }
			}
			
																		"AttachWearables"
				{
					"Wearable1" { "ItemDef" "4007" }
					"Wearable1" { "ItemDef" "4734" }
					"Wearable1" { "ItemDef" "4733" }
 					"Wearable1" { "ItemDef" "4760" }
					"Wearable1" { "ItemDef" "6204" }
					"Wearable1" { "ItemDef" "6203" }
					"Wearable1" { "ItemDef" "6202" }
 				
				}
								"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance"}
				"2"            	{"Item"        "item_shivas_guard"}

			}
		}
	}


	"npc_classic_pudge4"	
	{
	
		"vscripts"		"ai/ai_neutral_autocast.lua"
		"Model"						"models/heroes/pudge/pudge.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"5"
		"ModelScale" 				"2"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior" 	"0"
		"IsAncient"					"1"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"blood_effect"  
		"Ability3"					"pudge_meat_hook_2"	
		"Ability4"					"attack_of_deactivating"
		"Ability5"					"pudge_rot_passive"
		"Ability6"					"pudge_dismember_2"	
		"Ability7"					"respawn_zombie_big"	 
		"Ability8"					"hardskin_pudge"
 	 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"45"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"875"
		"AttackDamageMax"			"1100"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"700"
		"BountyGoldMin"				"870"	
		"BountyGoldMax"				"1200"		

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"325"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"5500"
		"StatusHealthRegen"			"50"
		"StatusMana"				"1250"	
		"StatusManaRegen"			"15.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
							"DisableResistance"			"70.0"
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
															"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9250" }
					"Wearable1" { "ItemDef" "9251" }
					"Wearable1" { "ItemDef" "9252" }
 					"Wearable1" { "ItemDef" "9253" }
					"Wearable1" { "ItemDef" "9254" }
					"Wearable1" { "ItemDef" "8010" }
					"Wearable1" { "ItemDef" "9256" }
 				
				}
								"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance"}
				"2"            	{"Item"        "item_shivas_guard"}

			}
		}
	}


	"npc_classic_pudge3"	
	{

		"vscripts"		"ai/ai_neutral_autocast.lua"
		"Model"						"models/heroes/pudge_cute/pudge_cute.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"5"
		"ModelScale" 				"2.5"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior" 	"0"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"blood_effect"  
		"Ability3"					"pudge_meat_hook_2"	
		"Ability4"					"attack_of_deactivating"
		"Ability5"					"pudge_rot_passive"
		"Ability6"					"pudge_dismember_2"	
		"Ability7"					"respawn_zombie_big"	 
		"Ability8"					"hardskin_pudge"
 	 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"45"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"875"
		"AttackDamageMax"			"1100"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	   		"IsAncient"					"1"

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"700"
		"BountyGoldMin"				"870"	
		"BountyGoldMax"				"1200"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"325"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"5500"
		"StatusHealthRegen"			"50"
		"StatusMana"				"1250"	
		"StatusManaRegen"			"15.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"



		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
							"DisableResistance"			"70.0"
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
						"AttachWearables"
				{
					"Wearable1" { "ItemDef" "696" }  
					"Wearable1" { "ItemDef" "13786" }
 				
				}
								"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance"}
				"2"            	{"Item"        "item_shivas_guard"}

			}
		}
	}


	"npc_classic_pudge2"	
	{

		"vscripts"		"ai/ai_neutral_autocast.lua"
		"Model"						"models/heroes/pudge/pudge.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"5"
		"ModelScale" 				"2"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior" 	"0"		
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"blood_effect"  
		"Ability3"					"pudge_meat_hook_2"	
		"Ability4"					"attack_of_deactivating"
		"Ability5"					"pudge_rot_passive_2"
		"Ability6"					"pudge_dismember_2"	
		"Ability7"					"respawn_zombie_big"	 
		"Ability8"					"hardskin_pudge"
 	 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"45"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"875"
		"AttackDamageMax"			"1100"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"700"
		"BountyGoldMin"				"870"	
		"BountyGoldMax"				"1200"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"325"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"5500"
		"StatusHealthRegen"			"50"
		"StatusMana"				"1250"	
		"StatusManaRegen"			"15.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"



		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
							"DisableResistance"			"70.0"
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
												"AttachWearables"
				{
					"Wearable1" { "ItemDef" "7742" }
					"Wearable1" { "ItemDef" "6825" }
					"Wearable1" { "ItemDef" "6226" }
 					"Wearable1" { "ItemDef" "5049" }
					"Wearable1" { "ItemDef" "7166" }
					"Wearable1" { "ItemDef" "6115" }
					"Wearable1" { "ItemDef" "7369" }
 				
				}
								"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance"}
				"2"            	{"Item"        "item_shivas_guard"}

			}
		}
	}


	"npc_classic_pudge"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/ai_neutral_autocast.lua"
		"Model"						"models/items/pudge/arcana/pudge_arcana_base.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"5"
		"ModelScale" 				"2"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior" 	"0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"blood_effect"  
		"Ability3"					"pudge_meat_hook_2"	
		"Ability4"					"attack_of_deactivating"
		"Ability5"					"pudge_rot_passive_3"
		"Ability6"					"pudge_dismember_2"	
		"Ability7"					"respawn_zombie_big"	 
		"Ability8"					"hardskin_pudge"
 	 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"45"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"875"
		"AttackDamageMax"			"1100"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"700"
		"BountyGoldMin"				"870"	
		"BountyGoldMax"				"1200"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"325"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"5500"
		"StatusHealthRegen"			"50"
		"StatusMana"				"1250"	
		"StatusManaRegen"			"15.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
							"DisableResistance"			"70.0"
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
									"AttachWearables"
				{
					"Wearable1" { "ItemDef" "6293" }
					"Wearable1" { "ItemDef" "13788" }
					"Wearable1" { "ItemDef" "13789" }
 					"Wearable1" { "ItemDef" "7756" }
					"Wearable1" { "ItemDef" "7993" }
					"Wearable1" { "ItemDef" "7172" }
					"Wearable1" { "ItemDef" "6299" }
 				
				}				
				"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance"}
				"2"            	{"Item"        "item_shivas_guard"}

			}
 
		}
	}


	"npc_classic_ghoul"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"ghoul_devourer"
		"Ability3"					"blood_effect"	
		"Ability4"					"attack_of_deactivating"
		"Ability5"					"respawn_strong"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"40"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"370"
		"AttackDamageMax"			"370"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"150"
		"BountyGoldMin"				"60"	
		"BountyGoldMax"				"120"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"270"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"500"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}

	"npc_classic_wave_pudge"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/pudge/pudge.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"4"
		"ModelScale" 				"0.8"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					""
		"Ability3"					"blood_effect"	
		"Ability4"					"attack_of_deactivating"
		"Ability5"		            "pudge_dismember_wave"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"60"
		"MagicalResistance"         "85"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"550"
		"AttackDamageMax"			"600"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"80"
		"BountyGoldMin"				"20"	
		"BountyGoldMax"				"27"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2250"
		"StatusHealthRegen"			"35.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
				
											"OffensiveAbilities"
			{
				"Ability5"
				{
					"Name"					"pudge_dismember_wave"										
				}
				
			}
						"AttachWearables"
				{
					"Wearable1" { "ItemDef" "14033" }
					"Wearable1" { "ItemDef" "14036" }
					"Wearable1" { "ItemDef" "14035" }
					"Wearable1" { "ItemDef" "14039" }
					"Wearable1" { "ItemDef" "14034" }
					"Wearable1" { "ItemDef" "14038" }
					"Wearable1" { "ItemDef" "14037" }
 				
				}
		}
	}
	
	"npc_classic_wave_ghoul"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"ghoul_devourer"
		"Ability3"					"blood_effect"	
		"Ability4"					"attack_of_deactivating"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"42"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"240"
		"AttackDamageMax"			"260"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"50"
		"BountyGoldMin"				"15"	
		"BountyGoldMax"				"20"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1800"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}

	"npc_classic_wave_ghost"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/neutral_creeps/n_creep_ghost_a/n_creep_ghost_a.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_magick_attack"
		"Ability2"					"ghost_elusive"
		"Ability3"					"attack_of_deactivating"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"28"
		"MagicalResistance"         "55"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "5000"
	    "AttackRange"           	"350"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"40"
		"BountyGoldMin"				"35"	
		"BountyGoldMax"				"40"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"300"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"775"
		"StatusHealthRegen"			"0"	
		"StatusMana"				"0"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"	
		"VisionNighttimeRange"		"900"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}	
	
	"npc_classic_wave_ghost_2"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/death_prophet/death_prophet.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_magick_attack_2"
		"Ability2"					"ghost_elusive"
		"Ability3"					"attack_of_deactivating"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"33"
		"MagicalResistance"         "65"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "5000"
	    "AttackRange"           	"350"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"60"
		"BountyGoldMin"				"65"	
		"BountyGoldMax"				"70"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"300"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1875"
		"StatusHealthRegen"			"0"	
		"StatusMana"				"0"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"	
		"VisionNighttimeRange"		"900"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
						"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9686" }
					"Wearable1" { "ItemDef" "9658" }
					"Wearable1" { "ItemDef" "9687" }
					"Wearable1" { "ItemDef" "9657" }
					"Wearable1" { "ItemDef" "9685" } 				
				}
		}
	}

	"npc_classic_wave_ghost_3"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/death_prophet/death_prophet.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_magick_attack_3"
		"Ability2"					"ghost_elusive"
		"Ability3"					"attack_of_deactivating"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"36"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.5"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "5000"
	    "AttackRange"           	"350"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"75"
		"BountyGoldMin"				"85"	
		"BountyGoldMax"				"90"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"300"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2475"
		"StatusHealthRegen"			"0.0"	
		"StatusMana"				"0"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"	
		"VisionNighttimeRange"		"900"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
						"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9686" }
					"Wearable1" { "ItemDef" "9658" }
					"Wearable1" { "ItemDef" "9687" }
					"Wearable1" { "ItemDef" "9657" }
					"Wearable1" { "ItemDef" "9685" } 				
				}
		}
	}
	
	"npc_classic_wave_ghost_boss"	
	{
		// General
		//----------------------------------------------------------------
       		"vscripts"		"ai/ai_ghost.lua"
		"Model"						"models/heroes/death_prophet/death_prophet.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"7"
		"ModelScale" 				"1.1"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_magick_attack_boss"
		"Ability2"					"death_prophet_silence_boss" 
		"Ability3"					"attack_of_deactivating"	
		"Ability4"					"ghost_elusive"
		"Ability5"                  "death_prophet_spirit_siphon_boss"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"44"
		"MagicalResistance"         "85"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.45"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "5000"
	    "AttackRange"           	"350"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"75"
		"BountyGoldMin"				"85"	
		"BountyGoldMax"				"90"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"300"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2475"
		"StatusHealthRegen"			"0.0"	
		"StatusMana"				"1250"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"	
		"VisionNighttimeRange"		"900"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{

						"AttachWearables"
				{
					"Wearable1" { "ItemDef" "7317" }
					"Wearable1" { "ItemDef" "7205" }
					"Wearable1" { "ItemDef" "7206" }
					"Wearable1" { "ItemDef" "12931" }
					"Wearable1" { "ItemDef" "9685" } 				
				}
				
											"OffensiveAbilities"
			{
				"Ability5"
				{
					"Name"					"death_prophet_spirit_siphon_boss"										
				}
				
			}
		}
	}
	

	"npc_classic_witch"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/death_prophet/death_prophet.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"15"
		"ModelScale" 				".9"
		"CanBeDominated"            "0"		
		"UseNeutralCreepBehavior"	"1"
		"IsAncient"					"1"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_boss_magick_attack"
		"Ability2"					"witch_death_aura"
		"Ability3"					"blood_effect"	
		"Ability4"					"attack_of_deactivating"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"20"
		"MagicalResistance"         "60"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "700"
	    "AttackRange"           	"700"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"300"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"170"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"3000"
		"StatusHealthRegen"			"30"	
		"StatusMana"				"0"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"700"	
		"VisionNighttimeRange"		"700"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{

			"AttachWearables"
			{
			    "Wearable1" { "ItemDef" "168" }
			    "Wearable2" { "ItemDef" "169" }
			}

			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}	


	"npc_boss_mutant"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_flesh_golem.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"25"
		"ModelScale" 				"1.0"
		"CanBeDominated"            "0"		
		"UseNeutralCreepBehavior"	"1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"mutant_dismemberment"
		"Ability3"					"mutant_reflector"	
		"Ability4"					"blood_effect"
		"Ability5"					"attack_of_deactivating"
		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"50"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"200"
		"AttackDamageMax"			"400"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"700"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"400"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"270"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"3000"
		"StatusHealthRegen"			"100.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"700"
		"VisionNighttimeRange"		"700"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}
 
 		"npc_tombstone1"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/heroes/undying/undying_tower.vmdl" 
	"SoundSet"					"Undying_Tombstone"					// Name of sound set.
       "IsAncient"                  "1"
		"wearable"				"8630" 
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"golden_mine_passive_2"			// Ability 1.
		"Ability2"					"pudge_rot_passive_tomb_1"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
 
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}

 		"npc_tombstone2"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/heroes/undying/undying_tower.vmdl" 
	"SoundSet"					"Undying_Tombstone"						// Name of sound set.
        "IsAncient"                  "1"
		"wearable"				"8630"		
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"golden_mine_passive_3"			// Ability 1.
		"Ability2"					"pudge_rot_passive_tomb_2"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"			// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}
	

 		"npc_tombstone3"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/heroes/undying/undying_tower.vmdl" 
	"SoundSet"					"Undying_Tombstone"					// Name of sound set.
        "IsAncient"                  "1"
				"wearable"				"8630"
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"golden_mine_passive_4"			// Ability 1.
		"Ability2"					"pudge_rot_passive_tomb_3"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"		// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
 
	}
	

 		"npc_tombstone4"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/heroes/undying/undying_tower.vmdl" 
	"SoundSet"					"Undying_Tombstone"					// Name of sound set.
        "IsAncient"                  "1"
				"wearable"				"8630"
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"golden_mine_passive_5"			// Ability 1.
		"Ability2"					"pudge_rot_passive_tomb_4"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"		// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}
	

 		"npc_tombstone_flash_1"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/items/undying/idol_of_ruination/idol_tower_gold_sim.vmdl" 
	"SoundSet"					"Undying_Tombstone"						// Name of sound set.
        "IsAncient"                  "1"
			"wearable"				"8630"	
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"golden_mine_passive_6"			// Ability 1.
		"Ability2"					"nevermore_dark_lord_1"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"			// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}
	
	 		"npc_tombstone_flash_2"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/items/undying/idol_of_ruination/idol_tower_sim.vmdl" 
	"SoundSet"					"Undying_Tombstone"						// Name of sound set.
        "IsAncient"                  "1"
			"wearable"				"8630"	
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"golden_mine_passive_6"			// Ability 1.
		"Ability2"					"abyssal_underlord_atrophy_aura_1"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"			// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}
	
	 		"npc_tombstone_flash_3"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/items/undying/idol_of_ruination/idol_tower_gold_sim.vmdl" 
	"SoundSet"					"Undying_Tombstone"						// Name of sound set.
        "IsAncient"                  "1"
			"wearable"				"8630"	
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"golden_mine_passive_7"			// Ability 1.
		"Ability2"					"nevermore_dark_lord_2"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"			// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}
	
	 		"npc_tombstone_flash_4"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/items/undying/idol_of_ruination/idol_tower_sim.vmdl" 
	"SoundSet"					"Undying_Tombstone"						// Name of sound set.
        "IsAncient"                  "1"
			"wearable"				"8630"	
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"golden_mine_passive_7"			// Ability 1.
		"Ability2"					"abyssal_underlord_atrophy_aura_2"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"			// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}

	"npc_boss_ghost"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/neutral_creeps/n_creep_ghost_a/n_creep_ghost_a.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.5"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_magick_attack"
		"Ability2"					"ghost_elusive"
		"Ability3"					"attack_of_deactivating"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"25"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "5000"
	    "AttackRange"           	"350"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"30"
		"BountyGoldMin"				"10"	
		"BountyGoldMax"				"30"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"300"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"250"
		"StatusHealthRegen"			"0.5"	
		"StatusMana"				"0"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"	
		"VisionNighttimeRange"		"5000"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}	


	"npc_boss_ghoul"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				"2.0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"ghoul_devourer"
		"Ability3"					"blood_effect"	
		"Ability4"					"attack_of_deactivating"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"40"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"370"
		"AttackDamageMax"			"370"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"60"
		"BountyGoldMin"				"20"	
		"BountyGoldMax"				"60"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"400"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}

}
