// Units File

"DOTAUnits"
{
 
//------first night---------

	"npc_classic_wave_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"2"
		"ModelScale" 				".9"
        "BoundsHullName"         "DOTA_HULL_SIZE_REGULAR"
		"UseNeutralCreepBehavior"	"0"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"slow_mobs"
		"Ability2"					""
		"Ability3"					"zombie_passive"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"2"
		"MagicalResistance"         "15"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"67"
		"AttackDamageMax"			"77"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"1100"
		"AttackRange"				"130"
        "BaseAttackSpeed"			"140"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"10"
		"BountyGoldMin"				"5"	
		"BountyGoldMax"				"8"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"225"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
 
	}
	

 "npc_suic_wave_zombie"	
	{
 		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"2"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"0"
 

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"zombie_suic"
		"Ability2"					"slow_mobs"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"		            "zombie_passive"
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"4"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"90"
		"AttackDamageMax"			"167"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"1100"
		"AttackRange"				"120"
        "BaseAttackSpeed"			"140"	  

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"23"
		"BountyGoldMin"				"18"	
		"BountyGoldMax"				"25"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"615"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
 
	}
	

"npc_undying_1"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undying.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"4"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_1"
		"Ability2"					"slow_mobs"
		"Ability3"					""	
		"Ability4"					""
 		"Ability5"		"zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"3"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"140"
		"AttackDamageMax"			"197"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"1100"
		"AttackRange"				"180"
        "BaseAttackSpeed"			"140"	 	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"80"
		"HealthBarOffset"			"245"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"120"
		"BountyGoldMin"				"20"	
		"BountyGoldMax"				"20"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2750"
		"StatusHealthRegen"			"0"
		"StatusMana"				"550"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "392" }
					"Wearable1" { "ItemDef" "393" }
					"Wearable1" { "ItemDef" "542" }
					"Wearable1" { "ItemDef" "616" }
 
 
 				
				}
 	
			
		}
	}
 

//------second night---------

"npc_classic_wave_big_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"4"
		"ModelScale" 				"1.5"
        "BoundsHullName"         "DOTA_HULL_SIZE_REGULAR"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"slow_mobs"
		"Ability2"					""
		"Ability3"					"zombie_passive"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"3"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"315"
		"AttackDamageMax"			"345"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"125"
        "BaseAttackSpeed"			"100"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"50"
		"HealthBarOffset"			"190"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"46"
		"BountyGoldMin"				"10"	
		"BountyGoldMax"				"15"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"850"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
 
	}


	"npc_wave_zombie_toxic"	
	{
 
 		"vscripts"		            "ai/ai_toxic.lua"      
		"Model"						"models/heroes/undying/undying_flesh_golem_rubick.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"4"
		"ModelScale" 				"0.6"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"spider_explode_lua_2"
		"Ability2"					"slow_mobs"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"		            "zombie_passive"
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"6"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"450"
		"AttackDamageMax"			"590"
		"AttackRate"				"2.2"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
        "BaseAttackSpeed"			"140"	 	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"50"
		"BountyGoldMin"				"20"	
		"BountyGoldMax"				"30"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"925"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{

			"EquippedItems"
			{
				"1"            	{"Item"        "item_toxic_boots"}
			}
		}
	}
	

	"npc_undying_2"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/ai_undying.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"5"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_2"
		"Ability2"					"slow_mobs"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"		"zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"4"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"775"
		"AttackDamageMax"			"830"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"180"
        "BaseAttackSpeed"			"140"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"80"
		"HealthBarOffset"			"245"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"325"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"750"
		"StatusHealthRegen"			"0"
		"StatusMana"				"700"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "13484" }
					"Wearable1" { "ItemDef" "13483" }
					"Wearable1" { "ItemDef" "542" }  
					"Wearable1" { "ItemDef" "13482" }
 					"Wearable1" { "ItemDef" "13453" }
 				
				}
	
			
		}
	}

//------third night--------- 

"npc_classic_wave_ghoul"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"5"
		"ModelScale" 				"1.0"
		"BoundsHullName"         "DOTA_HULL_SIZE_REGULAR"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_lifesteal"
		"Ability2"					"slow_mobs"
		"Ability3"					""	
		"Ability4"					"ghoul_crazy_look"
		"Ability5"                  "zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"6"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"4055"
		"AttackDamageMax"			"5275"
		"AttackRate"				"2.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"125"
        "BaseAttackSpeed"			"160"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"50"
		"HealthBarOffset"			"190"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"40"
		"BountyGoldMin"				"12"	
		"BountyGoldMax"				"18"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2600"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
 
	}


	"npc_undying_3"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undying.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"7"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_3"
		"Ability2"					"ghoul_crazy_look"
		"Ability3"					""	
		"Ability4"					"slow_mobs"
		"Ability5"		"zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"8"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"3525"
		"AttackDamageMax"			"4675"
		"AttackRate"				"3.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"180"
        "BaseAttackSpeed"			"140"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"650"
		"BountyGoldMin"				"185"	
		"BountyGoldMax"				"200"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"6750"
		"StatusHealthRegen"			"0"
		"StatusMana"				"1100"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9913" }
					"Wearable1" { "ItemDef" "9910" }
					"Wearable1" { "ItemDef" "542" }  
					"Wearable1" { "ItemDef" "7938" }
 					"Wearable1" { "ItemDef" "13453" }
 				
				}
 	
			
		}
	}
	
 
//------fourth night--------- 


"npc_classic_wave_ghoul_2"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"6"
		"ModelScale" 				"1.0"
		"BoundsHullName"         "DOTA_HULL_SIZE_REGULAR"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_lifesteal"
		"Ability2"					""
		"Ability3"					"slow_mobs"	
		"Ability4"					"ghoul_crazy_look"
		"Ability5"                  "zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"6"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"6425"
		"AttackDamageMax"			"7475"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"125"
        "BaseAttackSpeed"			"160"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"50"
		"HealthBarOffset"			"190"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"56"
		"BountyGoldMin"				"12"	
		"BountyGoldMax"				"17"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"3200"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
 
        "Creature"
        {
        	"AttachWearables"
        	{
 					"Wearable1" { "ItemDef" "7475" }
 					"Wearable1" { "ItemDef" "7474" }
 					"Wearable1" { "ItemDef" "7473" }
 					"Wearable1" { "ItemDef" "7471" }

        	}
        }
        
	}

"npc_classic_wave_ghoul_big"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"10"
		"ModelScale" 				"1.9"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_lifesteal"
		"Ability2"					"slow_mobs"
		"Ability3"					"lifestealer_passive"	
		"Ability4"					"ghoul_crazy_look"
		"Ability5"                  "zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"18"
		"MagicalResistance"         "30"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"4450"
		"AttackDamageMax"			"5780"
		"AttackRate"				"6.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"125"
        "BaseAttackSpeed"			"160"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"80"
		"HealthBarOffset"			"230"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"250"
		"BountyGoldMin"				"50"	
		"BountyGoldMax"				"75"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"6000"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
    
        "Creature"
        {
        	"AttachWearables"
        	{
 					"Wearable1" { "ItemDef" "12934" }
 					"Wearable1" { "ItemDef" "9108" }
 					"Wearable1" { "ItemDef" "9107" }
 					"Wearable1" { "ItemDef" "9105" }

        	}
        }
	}

//------fifty night----------------

"npc_classic_wave_pudge"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/heroes/pudge/pudge.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"8"
		"ModelScale" 				"1.2"
		"BoundsHullName"         "DOTA_HULL_SIZE_REGULAR"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"slow_mobs"
		"Ability2"					"pudge_rot_passive_wave"
		"Ability3"					""	
		"Ability4"					"ghoul_crazy_look"
		"Ability5"                  "zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"12"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"5225"
		"AttackDamageMax"			"6875"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"125"
        "BaseAttackSpeed"			"100"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"50"
		"HealthBarOffset"			"190"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"90"
		"BountyGoldMin"				"25"	
		"BountyGoldMax"				"35"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"8200"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
   
        "Creature"
        {
        	"AttachWearables"
        	{
 					"Wearable1" { "ItemDef" "47" }
 					"Wearable1" { "ItemDef" "258" }
 					"Wearable1" { "ItemDef" "259" }
 					"Wearable1" { "ItemDef" "260" }
 					"Wearable1" { "ItemDef" "261" }
  					"Wearable1" { "ItemDef" "262" }

        	}
        }
	}

"npc_wave_zombie_toxic_2"	
	{
 
 		"vscripts"		            "ai/ai_toxic.lua"      
		"Model"						"models/heroes/undying/undying_flesh_golem_rubick.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"8"
		"ModelScale" 				"0.6"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"spider_explode_lua_3"
		"Ability2"					"slow_mobs"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"		            "zombie_passive"
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"4"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"7855"
		"AttackDamageMax"			"8955"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
        "BaseAttackSpeed"			"150"	 	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"120"
		"BountyGoldMin"				"40"	
		"BountyGoldMax"				"50"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2000"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{

			"EquippedItems"
			{
				"1"            	{"Item"        "item_toxic_boots"}
			}
		}
	}

//------sixty night----------------


"npc_classic_wave_pudge_2"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/heroes/pudge/pudge.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"9"
		"ModelScale" 				"1.0"
		"BoundsHullName"         "DOTA_HULL_SIZE_REGULAR"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"pudge_rot_passive_wave_2"
		"Ability3"					"slow_mobs"	
		"Ability4"					"ghoul_crazy_look"
		"Ability5"                  "zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"30"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"8500"
		"AttackDamageMax"			"9200"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"125"
        "BaseAttackSpeed"			"100"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"50"
		"HealthBarOffset"			"190"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"70"
		"BountyGoldMin"				"25"	
		"BountyGoldMax"				"35"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"9000"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
   
        "Creature"
        {
        	"AttachWearables"
        	{
 					"Wearable1" { "ItemDef" "47" }
 					"Wearable1" { "ItemDef" "258" }
 					"Wearable1" { "ItemDef" "259" }
 					"Wearable1" { "ItemDef" "260" }
 					"Wearable1" { "ItemDef" "261" }
  					"Wearable1" { "ItemDef" "262" }

        	}
        }
	}


"npc_classic_wave_pudge_mini"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/wave/ai_mini_pudge.lua"
		"Model"						"models/heroes/pudge/pudge.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"9"
		"ModelScale" 				"0.7"
		"BoundsHullName"         "DOTA_HULL_SIZE_REGULAR"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"pudge_dismember_wave"
		"Ability2"					"slow_mobs"
		"Ability3"					""	
		"Ability4"					"ghoul_crazy_look"
		"Ability5"                  "zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"24"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"11500"
		"AttackDamageMax"			"12800"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"125"
        "BaseAttackSpeed"			"100"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"50"
		"HealthBarOffset"			"190"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"68"
		"BountyGoldMin"				"25"	
		"BountyGoldMax"				"35"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"325"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"8000"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
   
        "Creature"
        {
        	"AttachWearables"
        	{
 					"Wearable1" { "ItemDef" "5046" }
 					"Wearable1" { "ItemDef" "5047" }
 					"Wearable1" { "ItemDef" "5048" }
 					"Wearable1" { "ItemDef" "5049" }
 					"Wearable1" { "ItemDef" "5050" }
  					"Wearable1" { "ItemDef" "5051" }

        	}
        }
	}

//------seventy night----------------


	"npc_classic_wave_greater_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/items/undying/idol_of_ruination/ruin_wight_minion_gold.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"10"
		"ModelScale" 				"1.0"
        "BoundsHullName"         "DOTA_HULL_SIZE_REGULAR"
		"UseNeutralCreepBehavior"	"0"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"slow_mobs"
		"Ability2"					""
		"Ability3"					"zombie_passive"	
		"Ability4"					"ghoul_crazy_look"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"14"
		"MagicalResistance"         "15"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"16000"
		"AttackDamageMax"			"17250"
		"AttackRate"				"2.2"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"1100"
		"AttackRange"				"125"
        "BaseAttackSpeed"			"140"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"50"
		"HealthBarOffset"			"190"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"80"
		"BountyGoldMin"				"30"	
		"BountyGoldMax"				"35"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"420"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"26000"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
 
	}

	"npc_classic_wave_reflect_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/items/undying/undying_fall20_immortal_head/undying_fall20_immortal_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"10"
		"ModelScale" 				"1.0"
        "BoundsHullName"         "DOTA_HULL_SIZE_REGULAR"
		"UseNeutralCreepBehavior"	"0"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"reflecting_zombie"
		"Ability2"					"slow_mobs"
		"Ability3"					"zombie_passive"	
		"Ability4"					"ghoul_crazy_look"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"10"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"11750"
		"AttackDamageMax"			"12200"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"1100"
		"AttackRange"				"125"
        "BaseAttackSpeed"			"180"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"50"
		"HealthBarOffset"			"190"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"150"
		"BountyGoldMin"				"50"	
		"BountyGoldMax"				"60"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"5500"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
 
	}
//------Lane Boss---------

	"npc_wave_boss_big_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"8"
		"ModelScale" 				"2.0"
        "BoundsHullName"         "DOTA_HULL_SIZE_HERO"
	 		"vscripts"                  "ai/boss_wave/ai_zombie.lua"
 				"UseNeutralCreepBehavior" 	"0"	
 						"ConsideredHero"			"1"
		"IsBossMonster"				"1"	
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"zombie_boss_poison_sting_big"
		"Ability2"					"wave_boss_aura"
 		"Ability3"					"zombie_passive"	
		"Ability4"					"slow_mobs"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"12"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"750"
		"AttackDamageMax"			"809"
		"AttackRate"				"2.5"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     
        "BaseAttackSpeed"			"135"	
		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"60"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"600"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"250"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4350"
		"StatusHealthRegen"			"10.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"750"
		"VisionNighttimeRange"		"750"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
 
	}
  
	"npc_wave_boss_half_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/undying/undying_fall20_immortal_head/undying_fall20_immortal_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"8"
		"ModelScale" 				"1.7"
        "BoundsHullName"         "DOTA_HULL_SIZE_HERO"
		"HasInventory"              "1"
 		"vscripts"                  "ai/boss_wave/ai_half_zombie.lua"
 				"UseNeutralCreepBehavior" 	"0"
 						"ConsideredHero"			"1"
		"IsBossMonster"				"1"	
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"wave_boss_aura"
		"Ability2"					"boss_zombie_open_wounds"
     	"Ability3"					"zombie_passive"	
		"Ability4"					"slow_mobs"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"4"
		"MagicalResistance"         "10"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"245"
		"AttackDamageMax"			"355"
		"AttackRate"				"1.5"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     
        "BaseAttackSpeed"			"135"	
		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"60"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"600"
		"BountyGoldMin"				"125"	
		"BountyGoldMax"				"250"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2850"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"750"
		"VisionNighttimeRange"		"750"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 

						"EquippedItems"
			{
				"1"            	{"Item"        "item_hyperstone"}
				"2"            	{"Item"        "item_hyperstone"}
 

			}				
		}

 	}
  






	"npc_wave_boss_suicide"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/courier/pw_zombie/pw_zombie_flying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"12"
		"ModelScale" 				"1.5"
  		"vscripts"                  "ai/boss_wave/ai_suicide.lua"
		"UseNeutralCreepBehavior" 	"0"
				"ConsideredHero"			"1"
		"IsBossMonster"				"1"	
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"wave_boss_aura"
	 	"Ability2"					"slow_mobs"
		"Ability3"					"suicide_boys"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"89"
		"MagicalResistance"         "40"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"1250"
		"BountyGoldMin"				"100"	
		"BountyGoldMax"				"200"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"100"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"18000"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"0"
		"VisionNighttimeRange"		"0"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
 
	}

	"npc_wave_boss_necr"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/necrolyte/necrolyte.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Necrolyte"
  		"vscripts"                  "ai/boss_wave/ai_necr.lua"
  		"UseNeutralCreepBehavior"	"0"
		"GameSoundsFile"			"soundevents/game_sounds_necrolyte.vsndevts"
		"Level"						"12"
		"ModelScale" 				"1.2"
		"CanBeDominated"            "0"		
 		"ConsideredHero"			"1"
		"IsBossMonster"				"1"	
		"IsAncient"					"1"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"rot_splesh"
		"Ability2"					"zombie_passive"
		"Ability3"					"wave_boss_aura"	
		"Ability4"					"slow_mobs"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"4"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"255"
		"AttackDamageMax"			"280"
		"AttackRate"				"2.3"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"1300"
		"ProjectileModel"			"particles/econ/items/necrolyte/necrophos_sullen_gold/necro_sullen_pulse_enemy_gold.vpcf"
		"ProjectileSpeed"			"600"			// Speed of projectile.		

        "BaseAttackSpeed"			"165"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"1250"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"315"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"5250"
		"StatusHealthRegen"			"0"	
		"StatusMana"				"0"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"700"	
		"VisionNighttimeRange"		"700"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{

			"AttachWearables"
			{
			    "Wearable1" { "ItemDef" "17930" }
			    "Wearable2" { "ItemDef" "17929" }
			    "Wearable2" { "ItemDef" "17928" }
			    "Wearable2" { "ItemDef" "17927" }
			    "Wearable2" { "ItemDef" "17926" }

			}
 
		}
	}	


	"npc_wave_boss_meat_golem"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/undying/flesh_golem/davy_jones_set_davy_jones_set_kraken/davy_jones_set_davy_jones_set_kraken.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"12"
		"ModelScale" 				"1.6"
		"HasInventory"              "1"
  		"vscripts"                  "ai/boss_wave/ai_golem.lua"
  		"UseNeutralCreepBehavior"	"0"
 		"ConsideredHero"			"1"
		"IsBossMonster"				"1"	 		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"undying_soul_rip_flash_1"
		"Ability2"					"mutant_reflector"
		"Ability3"					"zombie_passive"	
		"Ability4"					"wave_boss_aura"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"33"
		"MagicalResistance"         "30"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1405"
		"AttackDamageMax"			"2425"
		"AttackRate"				"2.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     
        "BaseAttackSpeed"			"135"	
		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"1250"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"		

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"285"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10000"
		"StatusHealthRegen"			"25.0"
		"StatusMana"				"1850"	
		"StatusManaRegen"			"3.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"525"
		"VisionNighttimeRange"		"525"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		"Creature"
		{
 

						"EquippedItems"
			{
				"1"            	{"Item"        "item_blade_mail"}
 

			}				
	}
 
	}


	"npc_wave_boss_ghost"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/death_prophet/death_prophet.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"15"
		"ModelScale" 				"1.2"
		"CanBeDominated"            "0"		
  		"vscripts"                  "ai/boss_wave/ai_ghost_boss.lua"
  		"UseNeutralCreepBehavior"	"0"
 		"ConsideredHero"			"1"
		"IsBossMonster"				"1"	
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"death_prophet_exorcism_boss_wave"
		"Ability2"					"pugna_life_drain_wave_boss"
		"Ability3"					"ghost_elusive_1"	
		"Ability4"					"range_magick_attack_2"
		"Ability5"                  "ghoul_crazy_look"
		"Ability6"                  "zombie_passive"
		"Ability7"                  "wave_boss_aura"
		   

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"12"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"2.3"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"450"
		"ProjectileModel"			"particles/econ/items/necrolyte/necrophos_sullen_gold/necro_sullen_pulse_enemy_gold.vpcf"
		"ProjectileSpeed"			"600"			// Speed of projectile.		

        "BaseAttackSpeed"			"220"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"3250"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"		

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"550"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"12500"
		"StatusHealthRegen"			"100.0"	
		"StatusMana"				"1800"
		"StatusManaRegen"			"10.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"700"	
		"VisionNighttimeRange"		"700"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

 		
		"Creature"
		{
		
	 

					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "5597" }
					"Wearable1" { "ItemDef" "5598" }
 					"Wearable1" { "ItemDef" "5599" }
  					"Wearable1" { "ItemDef" "5600" }		 		
    					"Wearable1" { "ItemDef" "5603" }		 		
				}		
			
		}

	}	

	"npc_wave_boss_undying"	
	{
		// General
		//----------------------------------------------------------------
		
  		"vscripts"                  "ai/boss_wave/ai_und_boss.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"15"
		"ModelScale" 				"1.35"
		"UseNeutralCreepBehavior"	"0"
 		"ConsideredHero"			"1"
		"IsBossMonster"				"1"	

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"undying_decay_boss_wave"
	 	"Ability2"					"zombie_passive"
		"Ability3"					"slow_mobs"	
		"Ability4"					"ghoul_crazy_look"
		"Ability5"                  "wave_boss_aura"		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"20"
		"MagicalResistance"         "30"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1511"
		"AttackDamageMax"			"2525"
		"AttackRate"				"2.3"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"180"
	     
        "BaseAttackSpeed"			"160"	
		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"3250"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"385"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10000"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1925"	
		"StatusManaRegen"			"5.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
	 

					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9031" }
					"Wearable1" { "ItemDef" "9032" }
 					"Wearable1" { "ItemDef" "9033" }
 				
				}		
			
		}
	}

	"npc_wave_boss_pudge"	
	{
   		"vscripts"                  "ai/boss_wave/ai_pudge.lua"
		"Model"						"models/heroes/pudge/pudge.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"15"
		"ModelScale" 				"2.5"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior" 	"0"
		"IsAncient"					"1"
			"ConsideredHero"			"1"
		"IsBossMonster"				"1"		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"pudge_dispersion"  
		"Ability3"					"pudge_spawn"	
		"Ability4"					"wave_boss_aura"
		"Ability5"					"slow_mobs"
		"Ability6"					""	
		"Ability7"					""	 
		"Ability8"					""
 	 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"
		"MagicalResistance"         "20"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"3100"
		"AttackDamageMax"			"4200"
		"AttackRate"				"2.3"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     
        "BaseAttackSpeed"			"135"	

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"3250"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"		

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"185"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"34000"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"



		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
					"DisableResistance"			"0.0"
 
 
			
   		"AttachWearables"
				{
					"Wearable1" { "ItemDef" "6212" }
					"Wearable1" { "ItemDef" "9231" }

 					"Wearable1" { "ItemDef" "7174" }
					"Wearable1" { "ItemDef" "7167" }  
 					"Wearable1" { "ItemDef" "7166" }  
 					"Wearable1" { "ItemDef" "7169" }  				
				}
 
		}
	}

	"npc_wave_boss_mini_pudge"	
	{
    		"vscripts"                  "ai/boss_wave/ai_mini_pudge.lua"
		"Model"						"models/heroes/pudge_cute/pudge_cute.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"15"
		"ModelScale" 				"1"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior" 	"0"
		"IsAncient"					"0"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"pudge_meat_hook_mini"
		"Ability2"					"pudge_rot_passive_mini"  
		"Ability3"					"pudge_dismember_mini"	
		"Ability4"					""
		"Ability5"					""
		"Ability6"					""	
		"Ability7"					"ghoul_crazy_look"	 
		"Ability8"					""
 	 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"1"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1250"
		"AttackDamageMax"			"2350"
		"AttackRate"				"2.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     
        "BaseAttackSpeed"			"135"	
		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"0"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"		

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"1075"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2800"
		"StatusHealthRegen"			"0"
		"StatusMana"				"1250"	
		"StatusManaRegen"			"8.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"



		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
					"DisableResistance"			"30.0"
 
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_hyperstone"}
 
 

			}				
 
 
		}
	}


	"npc_wave_boss_meat_golem_2"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/undying/flesh_golem/spring2021_bristleback_paganism_pope_golem/spring2021_bristleback_paganism_pope_golem.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"20"
		"ModelScale" 				"1.6"
		"HasInventory"              "1"
  		"vscripts"                  "ai/boss_wave/ai_golem.lua"
  		"UseNeutralCreepBehavior"	"0"
 		"ConsideredHero"			"1"
		"IsBossMonster"				"1"	 		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"smash_of_mutant"
		"Ability2"					""
		"Ability3"					"zombie_passive"	
		"Ability4"					"wave_boss_aura"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"32"
		"MagicalResistance"         "30"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"4850"
		"AttackDamageMax"			"15050"
		"AttackRate"				"2.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     
        "BaseAttackSpeed"			"135"	
		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"80"
		"HealthBarOffset"			"240"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"5000"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"		

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"285"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"25000"
		"StatusHealthRegen"			"100.0"
		"StatusMana"				"1850"	
		"StatusManaRegen"			"3.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		"Creature"
		{
 

						"EquippedItems"
			{
				"1"            	{"Item"        "item_blade_mail"}
 

			}				
	}
 
	}
 


	"npc_wave_boss_suicide_2"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/courier/gama_brothers/gama_brothers_flying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"24"
		"ModelScale" 				"1.5"
  		"vscripts"                  "ai/boss_wave/ai_suicide.lua"
		"UseNeutralCreepBehavior" 	"0"
				"ConsideredHero"			"1"
		"IsBossMonster"				"1"	
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"wave_boss_aura"
	 	"Ability2"					""
		"Ability3"					"suicide_boys"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"333"
		"MagicalResistance"         "40"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"50"
		"HealthBarOffset"			"220"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"6000"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"100"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"240000"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"0"
		"VisionNighttimeRange"		"0"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
 
	}


	"npc_wave_boss_undying_2"	
	{
		// General
		//----------------------------------------------------------------
		
  		"vscripts"                  "ai/boss_wave/ai_und_boss_2.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"28"
		"ModelScale" 				"1.35"
		"UseNeutralCreepBehavior"	"0"
 		"ConsideredHero"			"1"
		"IsBossMonster"				"1"	

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"undying_decay_boss_wave_2"
	 	"Ability2"					"zombie_passive"
		"Ability3"					""	
		"Ability4"					"ghoul_crazy_look"
		"Ability5"                  "wave_boss_aura"		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"45"
		"MagicalResistance"         "30"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"2825"
		"AttackDamageMax"			"3875"
		"AttackRate"				"2.3"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"180"
	     
        "BaseAttackSpeed"			"160"	
		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"7000"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"395"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"25000"
		"StatusHealthRegen"			"100"
		"StatusMana"				"1925"	
		"StatusManaRegen"			"5.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
	 

					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9716" }
					"Wearable1" { "ItemDef" "9717" }
 					"Wearable1" { "ItemDef" "9718" }
 				
				}		
			
		}
	}
	"npc_wave_boss_viper"	
	{
		// General
		//----------------------------------------------------------------
		
  		"vscripts"                  "ai/wave/ai_zombie.lua"
		"Model"						"models/heroes/viper/viper.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"28"
		"ModelScale" 				"1.35"
		"UseNeutralCreepBehavior"	"0"
 		"ConsideredHero"			"1"	
		"IsBossMonster"				"1"	

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_viper_corrosive_skin"
	 	"Ability2"					"zombie_passive"
		"Ability3"					""	
		"Ability4"					"ghoul_crazy_look"
		"Ability5"                  "wave_boss_aura"		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"16"
		"MagicalResistance"         "30"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"19825"
		"AttackDamageMax"			"20875"
		"AttackRate"				"4.9"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"180"
	     
        "BaseAttackSpeed"			"160"	
		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"7000"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"395"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"75909"
		"StatusHealthRegen"			"100"
		"StatusMana"				"1925"	
		"StatusManaRegen"			"5.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
	 

					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "19451" }
					"Wearable1" { "ItemDef" "18491" }
 					"Wearable1" { "ItemDef" "18489" }
 				
				}		
			
		}
	}
	"npc_classic_necr"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"                  "ai/wave/ai_zombie.lua"
		"Model"						"models/heroes/necrolyte/necrolyte.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Necrolyte"
		"GameSoundsFile"			"soundevents/game_sounds_necrolyte.vsndevts"
		"Level"						"9"
		"ModelScale" 				"1.2"
		"UseNeutralCreepBehavior"	"0"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"necrolyte_death_pulse"
		"Ability2"					"zombie_passive"
		"Ability3"					"phase_necr"
		"Ability4"					"necrolyte_heartstopper_aura_2"	   
		"Ability5"					""
		"Ability6"					"ghoul_crazy_look"
 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"32"
		"MagicalResistance"         "16"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"7120"
		"AttackDamageMax"			"9140"
		"AttackRate"				"2.5"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"550"
		"ProjectileModel"			"particles/econ/items/necrolyte/necrophos_sullen_gold/necro_sullen_pulse_enemy_gold.vpcf"
		"ProjectileSpeed"			"600"			// Speed of projectile.		

	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"175"
		"BountyGoldMin"				"140"	
		"BountyGoldMax"				"155"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"170"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"16666"
		"StatusHealthRegen"			"30.0"
		"StatusMana"				"800"	
		"StatusManaRegen"			"20.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "7427" }
					"Wearable1" { "ItemDef" "8043" }
					"Wearable1" { "ItemDef" "8044" }
					"Wearable1" { "ItemDef" "8045" }
 				
				}
				
							"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"necrolyte_death_pulse"										
				}
				
			}
		}
	}
	//funmode
	"npc_classic_big_pig_wave"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"					"ai/wave/ai_zombie.lua"
		"Model"						"models/props_gameplay/pig.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"2"
		"ModelScale" 				"1.3"
		"BoundsHullName"         "DOTA_HULL_SIZE_REGULAR"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"primal_beast_onslaught"
		"Ability2"					"zombie_passive"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"3"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1087"
		"AttackDamageMax"			"2000"
		"AttackRate"				"3.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"30"
		"BountyGoldMin"				"24"	
		"BountyGoldMax"				"30"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"460"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"275"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "40.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"primal_beast_onslaught"										
				}
				
			}
		}
	}
	"npc_boss_pig_wave"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"					"ai/wave/ai_zombie.lua"
		"Model"						"models/items/beastmaster/boar/legacy_of_the_nords_battle_boar/legacy_of_the_nords_battle_boar.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"10"
		"ModelScale" 				"1.65"
		"UseNeutralCreepBehavior"	"0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"zombie_passive"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"25"
		"MagicalResistance"         "40"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"785"
		"AttackDamageMax"			"915"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"125"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"1250"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"12500"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

 
	}
	"npc_boss_pig_pet_wave"	
	{
		// General
		//----------------------------------------------------------------
 		"vscripts"					"ai/wave/ai_zombie.lua"
		"Model"						"models/items/beastmaster/boar/legacy_of_the_nords_battle_boar/legacy_of_the_nords_battle_boar.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"		"Hero_Beastmaster"
		"GameSoundsFile"			"soundevents/game_sounds_beastmaster.vsndevts"
		"Level"						"10"
		"ModelScale" 				"1.65"
		"UseNeutralCreepBehavior"	"0"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"Bo_greater_bash"
		"Ability2"					"bo_eat_creeps"
		"Ability3"					"Bo_armor_aura"	
		"Ability4"					"zombie_passive"
		"Ability5"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"12"
		"MagicalResistance"         "35"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1800"
		"AttackDamageMax"			"2850"
		"AttackRate"				"1"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"125"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"0"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"600"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"55200"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1337"	
		"StatusManaRegen"			"7.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

 
	}
	"npc_wave_boss_suicide_fun"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/courier/pw_zombie/pw_zombie_flying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"12"
		"ModelScale" 				"1.5"
  		"vscripts"                  "ai/boss_wave/ai_suicide.lua"
		"UseNeutralCreepBehavior" 	"0"
				"ConsideredHero"			"1"
		"IsBossMonster"				"1"	
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"wave_boss_aura"
	 	"Ability2"					"slow_mobs"
		"Ability3"					"suicide_boys"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"
		"MagicalResistance"         "11"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"1250"
		"BountyGoldMin"				"100"	
		"BountyGoldMax"				"200"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"100"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4000"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"0"
		"VisionNighttimeRange"		"0"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
 
	}
	"npc_Edgard_wave"
	{
		// General
		//----------------------------------------------------------------
		"BaseClass"					"npc_dota_creature"
		"Model"						"models/heroes/omniknight/omniknight.vmdl"
		"vscripts"                  "ai/wave/ai_zombie.lua"
		"ModelScale"				"1.1"
		"Level"						"100"
		"HealthBarOffset"			"350"
		"HasInventory"				"0"
		"ConsideredHero"			"0"
		"IsNeutralUnitType"         "1"
		"IsAncient"                 "1"
 		"ConsideredHero"			"1"
 
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"Bo_greater_bash"
		"Ability2"					"zombie_passive"
		"Ability3"					"high_five"
		"Ability4"					""

		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"24"
		"MagicalResistance"			"0"
		
		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1"
		"AttackDamageMax"			"2"
		"AttackRange"				"550"		// Range within a target can be attacked.
		        "BaseAttackSpeed"			"200"		     

		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"0.0"
		"BountyGoldMax"				"0.0"
		
		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"
		"RingRadius"				"120"
		"CollisionSize"				"1"
		
		
		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"4250"
		
		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"7000"
		"StatusHealthRegen"			"11"
		"StatusMana"				"0"
		"StatusManaRegen"			"0"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1800"
		"VisionNighttimeRange"		"1800"
		
		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_GOODGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "4507" }
					"Wearable1" { "ItemDef" "44" }
 
 
 				
				}
				"OffensiveAbilities"
			{
				"Ability3"
				{
					"Name"					"high_five"										
				}
				
			}
		}	
	}
	"npc_dota_creature_sand_king"
	{
		// Script
		"vscripts"	"ai/rhyzik.lua"
		// General
		// ----------------------------------------------------------------
		"BaseClass"	"npc_dota_creature"
		"Model"	"models/heroes/sand_king/sand_king.vmdl"
		"Level"	"30"
		"ModelScale"	"1.8"
		"ConsideredHero"	"1"
		"IsAncient"	"1"
		// Abilities
		// ----------------------------------------------------------------
		"Ability1"	"sand_king_boss_burrow"
		"Ability2"	"sand_king_boss_unburrow"
		"Ability3"	"sand_king_tail_swipe_right"
		"Ability4"	"sand_king_tail_swipe_left"
		"Ability5"	"sand_king_boss_move_back"
		"Ability6"	"sand_king_boss_burrowstrike"
		"Ability7"	"sand_king_boss_sandstorm"
		"Ability8"	"sand_king_boss_epicenter"
		"Ability9"	"sand_king_boss_passive"
		"Ability10"	"sand_king_burrowed_forward_strike"
		"Ability11"	"sand_king_burrowed_backward_strike"
		"Ability12"	"sand_king_boss_move_right"
		"Ability13"	"sand_king_boss_move_left"
		// Armor
		// ----------------------------------------------------------------
		"ArmorPhysical"	"120"
		// Attack
		// ----------------------------------------------------------------
		"AttackCapabilities"	"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"	"2500"
		"AttackDamageMax"	"3850"
		"AttackRate"	"0.8"
		"AttackAnimationPoint"	"0.53"
		"AttackAcquisitionRange"	"1800"
		"AttackRange"	"300"
		"ProjectileSpeed"	"0"
		// Bounds
		// ----------------------------------------------------------------
		"RingRadius"	"40"
		"HealthBarOffset"	"250"
		"BoundsHullName"	"DOTA_HULL_SIZE_HUGE"
		// Bounty
		// ----------------------------------------------------------------
		"BountyXP"	"1000"
		"BountyGoldMin"	"500"
		"BountyGoldMax"	"1000"
		// Movement
		// ----------------------------------------------------------------
		"MovementCapabilities"	"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"	"450"
		"MovementTurnRate"	"0.5"
		// Status
		// ----------------------------------------------------------------
		"StatusHealth"	"2000000"
		"StatusHealthRegen"	"10"
		"StatusMana"	"10000"
		"StatusManaRegen"	"150"
		// Vision
		// ----------------------------------------------------------------
		"VisionDaytimeRange"	"1800"
		"VisionNighttimeRange"	"1800"
		// Team
		// ----------------------------------------------------------------
		"TeamName"	"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"	"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"	"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"	"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		"HasInventory"	"1"
		// Creature Data
		// ----------------------------------------------------------------
		"Creature"
		{
			"EquippedItems"
			{
				"Sphere"
				{
					"Item"	"item_sphere"
				}
			}
			"AttachWearables"
			{
				"Wearable1"
				{
					"ItemDef"	"9432"
				}
				"Wearable2"
				{
					"ItemDef"	"9431"
				}
				"Wearable3"
				{
					"ItemDef"	"9433"
				}
				"Wearable4"
				{
					"ItemDef"	"9430"
				}
				"Wearable5"
				{
					"ItemDef"	"9429"
				}
			}
		}
	}


}
