// Units File

"DOTAUnits"
{
	"Version"	"1"
	
// Wave undyings

 
	

	"npc_seerdying_2"	
	{
	// General
	//
	"vscripts"					"ai/ai_leshrac.lua"
	"BaseClass"					"npc_dota_creature"
	"Model"						"models/heroes/leshrac/leshrac.vmdl"	// Model.
	"SoundSet"					"Hero_leshrac"					// Name of sound set.
	"IsBossMonster"				"1"
	"ModelScale"				"1.4"
	"Level"						"8"
	"MinimapIcon"							"minimap_death"
	"MinimapIconSize"						"550"
	
	// Abilities
	//----------------------------------------------------------------
	
	"Ability1"					"custom_thundercall"			// Ability 1.
	"Ability2"					"npc_leshrac_split_earth"			// Ability 2.
	"Ability3"					"custom_leshrac_diabolic_edict"			// Ability 3.
	"Ability4"					""			// Ability 4.
	"Ability5"					""			// Ability 5.
	"Ability6"					""			// Ability 6 - Extra.
	"Ability7"					""			// Ability 7 - Extra.
	"Ability8"					""			// Ability 8 - Extra.

	// Armor
	//----------------------------------------------------------------
	"ArmorPhysical"				"12"			// Physical protection.
	"MagicalResistance"			"25"		// Magical protection.

	// Attack
	//----------------------------------------------------------------
	"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
	"AttackDamageMin"			"195"		// Damage range min.
	"AttackDamageMax"			"210"		// Damage range max.
	"AttackRate"				"1.1"		// Speed of attack.
	"AttackAnimationPoint"		"0.3"		// Normalized time in animation cycle to attack.
	"AttackAcquisitionRange"	"1000"		// Range within a target can be acquired.
	"AttackRange"				"500"		// Range within a target can be attacked.
	"ProjectileModel"			"particles/units/heroes/hero_leshrac/leshrac_base_attack.vpcf"						// Particle system model for projectile.
	"ProjectileSpeed"			"800"			// Speed of projectile.

	// Bounty
	//----------------------------------------------------------------
	"BountyXP"					"3000"		// Experience earn.
	"BountyGoldMin"				"800"		// Gold earned min.
	"BountyGoldMax"				"1100"		// Gold earned max.

	// Bounds
	//----------------------------------------------------------------
	"RingRadius"				"70"
	"HealthBarOffset"			"160"
	"BoundsHullName"			"DOTA_HULL_SIZE_SMALL"	

	// Movement
	//----------------------------------------------------------------
	"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"			// Type of locomotion - ground, air
	"MovementSpeed"				"295"		// Speed
	"MovementTurnRate"			"0.5"		// Turning rate.

	
	"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_leshrac.vsndevts"
	"VoiceFile"					"soundevents/voscripts/game_sounds_vo_leshrac.vsndevts"

	// Status
	//----------------------------------------------------------------
	"StatusHealth"				"9500"		// Base health.
	"StatusHealthRegen"			"90"		// Health regeneration rate.
	"StatusMana"				"20000"			// Base mana.
	"StatusManaRegen"			"500"			// Mana regeneration rate.

	// Team
	//----------------------------------------------------------------
	"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
	"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
	"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
	"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
	
	// Vision
	//----------------------------------------------------------------
	"VisionDaytimeRange"		"1400"		// Range of vision during day light.
	"VisionNighttimeRange"		"1400"		// Range of vision at night time.

	// Creature Data
	//----------------------------------------------------------------------------------------------------------------------
	"Creature"
	{
		"DisableClumpingBehavior"   "1"
		"CanRespawn"				"0"
		"States"
		{
			"Invade"
			{
				"Name"				"Invade"
				"Aggression"		"100.0"
				"Avoidance"			"0.0"
				"Support"			"0.0"
				//"RoamDistance"		"700.0"
			}
		}

		"DefaultState"				"Invade"
		
		"OffensiveAbilities"
		{
			"Ability1"				
			{
				"Name"				"custom_thundercall"
				"Radius"			"500"
			}
			"Ability2"				
			{
				"Name"				"npc_leshrac_split_earth"
			}
			"Ability3"				
			{
				"Name"				"custom_leshrac_diabolic_edict"
			}
		}
		"AttachWearables"
		{
			"Wearable1"	{ "ItemDef"	"8110" }
			"Wearable2" { "ItemDef" "8111" }
			"Wearable3" { "ItemDef" "8112" }
			"Wearable4" { "ItemDef" "8113" }
			"Wearable5" { "ItemDef" "7596" }			
		}
	}
}
	

	"npc_seerdying_3"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"					"ai/ai_npc_witch.lua"
		"Model"						"models/heroes/death_prophet/death_prophet.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Ranged"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"30"
		"ModelScale" 				"1.7"
		"IsAncient"					"1"
		"ConsideredHero"			"1"
		"CanBeDominated"            "0"
		"IsBossMonster"				"1"
		"MinimapIcon"				"minimap_death"
		"MinimapIconSize"			"550"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"death_prophet_exorcism"
		"Ability3"					"rupture_custom"
		"Ability4"					""
		"Ability5"					""
		"Ability6"					""
		"Ability7"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"15"			// Physical protection.
		"MagicalResistance"         "25"
		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1500"		// Damage range min.
		"AttackDamageMax"			"2500"		// Damage range max.
		"AttackRate"				"1"		// Speed of attack.
		"AttackAnimationPoint"		"0.2"		// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"800"		// Range within a target can be acquired.
		"AttackRange"				"600"		// Range within a target can be attacked.
		"ProjectileSpeed" 			"900"
		"ProjectileModel" 			"particles/neutral_fx/ghost_base_attack.vpcf"
		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"250"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"8000"		// Experience earn.
		"BountyGoldMin"				"900"		// Gold earned min.
		"BountyGoldMax"				"1400"		// Gold earned max.

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"325"		// Speed.


		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10500"		// Base health.
		"StatusHealthRegen"			"120"		// Health regeneration rate.
		"StatusMana"				"1000"			// Base mana.
		"StatusManaRegen"			"100.0"		// Mana regeneration rate.

		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1600"		// Range of vision during day light.
		"VisionNighttimeRange"		"1600"		// Range of vision at night time.


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"						// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_HERO"
 		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{


			"AttachWearables"
			{
			    "Wearable1" { "ItemDef" "168" }
			    "Wearable2" { "ItemDef" "169" }
			}
			"DisableResistance"		"50"
			"DefaultState"			"Invade"
				"States"
				{
					"Invade"
					{
						"Name"				"Invade"
						"Aggression"		"50.0" //cast offensive spells whenever
						"Avoidance"			"0.0" //dont flee
						"Support"			"0.0" //start buffing
					}
				}
			"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"				"death_prophet_exorcism"
					"AOE"				"1"
					"Radius"			"600"
					"MinimumTargets"	"1"
				}
				"Ability2"
				{
					"Name"			"witch_doctor_maledict"
				}
			}

			//Level Up
			"HPGain"					"50"
			"DamageGain"				"2"
			"ArmorGain"					"0.25"
			"MagicResistGain"			"0.1"
			"MoveSpeedGain"				"1"
			"BountyGain"				"3"
			"XPGain"					"15"
			"ItemDrops"
            {


                "StatTomes"
                {
                    "Item"
                    {
  //                      "1"             "item_roshan_legs"
                    }
                    "Chance"            "100"
                }
			}
		}
	}
	
	"npc_seerdying_4"	
	{
    "Model"                                 "models/heroes/witchdoctor/witchdoctor.vmdl"
    "BaseClass"                             "npc_dota_creature"
    "SoundSet"                              "Hero_WitchDoctor"
    "GameSoundsFile"						"soundevents/game_sounds_heroes/game_sounds_witchdoctor.vsndevts"
    "Level"                                 "5"
    "ModelScale"                            "1.35"
    "CanBeDominated"						"0"
    "ConsideredHero"						"1"
    "HasInventory"							"1"
	"MinimapIcon"							"minimap_death"
	"MinimapIconSize"						"550"

    "precache"
    {
        "model"					            "models/heroes/witchdoctor/witchdoctor_ward.vmdl"
        "particle_folder"		            "particles/units/heroes/hero_witchdoctor"
    }

    "Ability1"					            "custom_paralyzing_cask"
    "Ability2"					            "custom_maledict"
    "Ability3"					            "custom_death_ward"
	"Ability4"					            "custom_paralyzing_cask_wrapper"
	"Ability5"					            "custom_maledict_wrapper"

    "ArmorPhysical"                         "5"
    "AttackCapabilities"            		"DOTA_UNIT_CAP_RANGED_ATTACK"
    "AttackDamageMin"                       "200"
    "AttackDamageMax"                       "300"
    "AttackRate"                            "0.8"
    "AttackAnimationPoint"         		    "0.4"
    "AttackAcquisitionRange"       		    "1600"
    "AttackRange"                           "550"
    "ProjectileModel"                       "particles/units/heroes/hero_witchdoctor/witchdoctor_base_attack.vpcf"
    "ProjectileSpeed"                       "1000"
    "RingRadius"                            "150"
    "HealthBarOffset"                       "300"
    "BountyXP"                              "1500"
    "BountyGoldMin"                         "500"
    "BountyGoldMax"                         "500"
    "MovementCapabilities"          		"DOTA_UNIT_CAP_MOVE_GROUND"
    "MovementSpeed"                         "330"
	"StatusHealth"							"8000"
	"StatusHealthRegen"						"90"
	"StatusMana"							"12000"
	"StatusManaRegen"						"500"
    "VisionDaytimeRange"            		"1600"
    "VisionNighttimeRange"          		"1600"
    "TeamName"                              "DOTA_TEAM_BADGUYS"
    "CombatClassAttack"						"DOTA_COMBAT_CLASS_ATTACK_HERO"
    "CombatClassDefend"						"DOTA_COMBAT_CLASS_DEFEND_HERO"
    "UnitRelationshipClass"         		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

    "Creature"
    {
		"DisableClumpingBehavior"   "1"
        "OffensiveAbilities"
        {
            "Ability4"
            {
                "Name"               "custom_paralyzing_cask_wrapper"
            }
            "Ability5"
            {
                "Name"               "custom_maledict_wrapper"
                "AOE"                "1"
                "Radius"             "300"
                "MinimumTargets"     "1"
            }
            "Ability3"
            {
                "Name"               "custom_death_ward"
                "AOE"                "1"
                "Radius"             "300"
                "MinimumTargets"     "1"
            }
        }
        "EquippedItems"
        {
            "Ultimate Scepter"       	{ "Item"        "item_ultimate_scepter" }
        }
        "AttachWearables"
        {
            "1" { "ItemDef"     "14975"  }
            "2" { "ItemDef"     "12328"  }
            "3" { "ItemDef"     "9679"  }
        }
    }
}
	
	

	"npc_undying"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undying.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_1"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""
		"Ability5"		"zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"8"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"105"
		"AttackDamageMax"			"115"
		"AttackRate"				"1.1"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"180"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"160"
		"BountyGoldMin"				"100"	
		"BountyGoldMax"				"120"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1450"
		"StatusHealthRegen"			"0"
		"StatusMana"				"550"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "392" }
					"Wearable1" { "ItemDef" "393" }
					"Wearable1" { "ItemDef" "542" }
					"Wearable1" { "ItemDef" "616" }
					"Wearable1" { "ItemDef" "13453" }
 
 				
				}
 	
			
		}
	}
	

	"npc_undying_2"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undying.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_2"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""
				"Ability5"		"zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"12"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"195"
		"AttackDamageMax"			"210"
		"AttackRate"				"1.1"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"180"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"325"
		"BountyGoldMin"				"200"	
		"BountyGoldMax"				"230"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2550"
		"StatusHealthRegen"			"0"
		"StatusMana"				"700"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "13484" }
					"Wearable1" { "ItemDef" "13483" }
					"Wearable1" { "ItemDef" "542" }  
					"Wearable1" { "ItemDef" "13482" }
 					"Wearable1" { "ItemDef" "13453" }
 				
				}
	
			
		}
	}
	

	"npc_undying_3"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undying.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_3"
		"Ability2"					"ghoul_crazy_look"
		"Ability3"					""	
		"Ability4"					""
				"Ability5"		"zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"18"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"450"
		"AttackDamageMax"			"500"
		"AttackRate"				"1.1"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"180"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"650"
		"BountyGoldMin"				"420"	
		"BountyGoldMax"				"450"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"3750"
		"StatusHealthRegen"			"0"
		"StatusMana"				"1100"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9913" }
					"Wearable1" { "ItemDef" "9910" }
					"Wearable1" { "ItemDef" "542" }  
					"Wearable1" { "ItemDef" "7938" }
 					"Wearable1" { "ItemDef" "13453" }
 				
				}
 	
			
		}
	}
	
	"npc_undying_4"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undying.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.2"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_4"
		"Ability2"					"ghoul_crazy_look"
		"Ability3"					""	
		"Ability4"					""
				"Ability5"		"zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"25"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"840"
		"AttackDamageMax"			"1050"
		"AttackRate"				"1.1"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"180"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"860"
		"BountyGoldMin"				"620"	
		"BountyGoldMax"				"850"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"5250"
		"StatusHealthRegen"			"0"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "12499" }
					"Wearable1" { "ItemDef" "12497" }
					"Wearable1" { "ItemDef" "542" }  
					"Wearable1" { "ItemDef" "7938" }
 					"Wearable1" { "ItemDef" "13453" }
 				
				}
 	
			
		}
	}
	
	
	"npc_zombie_toxic"	
	{
 
 		"vscripts"		"ai/ai_toxic.lua"      
		"Model"						"models/heroes/undying/undying_flesh_golem_rubick.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".5"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"spider_explode_lua"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""
		"Ability5"		"zombie_passive"
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"6"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"24"
		"AttackDamageMax"			"26"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
        "BaseAttackSpeed"			"220"	  

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"20"
		"BountyGoldMin"				"5"	
		"BountyGoldMax"				"15"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"250"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
									"EquippedItems"
			{
				"1"            	{"Item"        "item_toxic_boots"}
 

			}
		}
	}
	
	
	"npc_zombie_toxic_2"	
	{
 
 		"vscripts"		"ai/ai_toxic.lua"      
		"Model"						"models/heroes/undying/undying_flesh_golem_rubick.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".6"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"spider_explode_lua_2"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""
		"Ability5"		"zombie_passive"
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"9"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"220"
		"AttackDamageMax"			"230"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
        "BaseAttackSpeed"			"220"	 	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"50"
		"BountyGoldMin"				"20"	
		"BountyGoldMax"				"30"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"350"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
									"EquippedItems"
			{
				"1"            	{"Item"        "item_toxic_boots"}
 

			}
		}
	}
	
	
	"npc_zombie_toxic_3"	
	{
 
 		"vscripts"		"ai/ai_toxic.lua"      
		"Model"						"models/heroes/undying/undying_flesh_golem_rubick.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".7"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"spider_explode_lua_3"
		"Ability2"					""
		"Ability3"					"ghoul_crazy_look"	
		"Ability4"					""
		"Ability5"		"zombie_passive"
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"14"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"360"
		"AttackDamageMax"			"380"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
        "BaseAttackSpeed"			"220"	 	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"235"
		"BountyGoldMin"				"60"	
		"BountyGoldMax"				"80"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"500"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
									"EquippedItems"
			{
				"1"            	{"Item"        "item_toxic_boots"}
 

			}
		}
	}
	
	
	"npc_zombie_toxic_4"	
	{
 
 		"vscripts"		"ai/ai_toxic.lua"      
		"Model"						"models/heroes/undying/undying_flesh_golem_rubick.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".8"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"spider_explode_lua_4"
		"Ability2"					""
		"Ability3"					"ghoul_crazy_look"	
		"Ability4"					""
		"Ability5"		"zombie_passive"
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"20"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"425"
		"AttackDamageMax"			"525"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
        "BaseAttackSpeed"			"220"	 	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"420"
		"BountyGoldMin"				"120"	
		"BountyGoldMax"				"180"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"800"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
									"EquippedItems"
			{
				"1"            	{"Item"        "item_toxic_boots"}
 

			}
		}
	}
	
 
	
 

 

// Boss

	"npc_boss_pig"	
	{
		// General
		//----------------------------------------------------------------
 	
		"Model"						"models/items/beastmaster/boar/legacy_of_the_nords_battle_boar/legacy_of_the_nords_battle_boar.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"10"
		"ModelScale" 				"1.65"
		"UseNeutralCreepBehavior"	"1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"bo_eat"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"12"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"285"
		"AttackDamageMax"			"315"
		"AttackRate"				"1"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"125"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"1250"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"385"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"12500"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

 
	}
	
	"npc_boss_dead_pig"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/ai_boss_dead_pig.lua"		
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"15"
		"ModelScale" 				"2.5"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"              "1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"dead_stealer_feast"
		"Ability2"					"pig_dead_open_wounds"
		"Ability3"					"lifestealer_passive"	
		"Ability4"					""
		"Ability5"					"aghsfort_lifestealer_enraged_pulse"
		"Ability6"					"ghoul_crazy_look"
		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"52"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"895"
		"AttackDamageMax"			"1350"
		"AttackRate"				"1.15"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"7230"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"12500"
		"StatusHealthRegen"			"35"
		"StatusMana"				"2500"	
		"StatusManaRegen"			"3.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"850"
		"VisionNighttimeRange"		"850"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9215" }
					"Wearable1" { "ItemDef" "13787" }
					"Wearable1" { "ItemDef" "12934" }
					"Wearable1" { "ItemDef" "6475" }
				}
				
		
 			"DisableResistance"			"80.0"
			
		"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance_dead_boss"}
				"2"            	{"Item"        "item_assault_dead_boss"}
 
			}
		}
		
	}


//Xuita

	"npc_boss_pig_pet"	
	{
		// General
		//----------------------------------------------------------------
 	
		"Model"						"models/items/beastmaster/boar/legacy_of_the_nords_battle_boar/legacy_of_the_nords_battle_boar.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"		"Hero_Beastmaster"
		"GameSoundsFile"			"soundevents/game_sounds_beastmaster.vsndevts"
		"Level"						"10"
		"ModelScale" 				"1.65"
		"UseNeutralCreepBehavior"	"1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"Bo_greater_bash"
		"Ability2"					"bo_eat_creeps"
		"Ability3"					"Bo_armor_aura"	
		"Ability4"					""
		"Ability5"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"32"
		"MagicalResistance"         "35"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"800"
		"AttackDamageMax"			"850"
		"AttackRate"				"1"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"125"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"0"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"425"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"15200"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1337"	
		"StatusManaRegen"			"7.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

 
	}

	"npc_cemetery_skelet"	
	{
		// General
		//----------------------------------------------------------------
        "vscripts"        "ai/ai_cemetery_skelet.lua"
		"Model"						"models/creeps/neutral_creeps/n_creep_troll_skeleton/n_creep_skeleton_melee.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.15"
		"UseNeutralCreepBehavior" 	"0"
		"HasInventory"				"1"
		"IsAncient"					"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"zombie_passive"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					""    
		"Ability6"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"12"
		"MagicalResistance"         "30"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"182"
		"AttackDamageMax"			"190"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"185"
		"BountyGoldMin"				"65"	
		"BountyGoldMax"				"70"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2200"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_hyperstone"}

			}	
		}
	}

	"npc_classic_pig"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/props_gameplay/pig.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn_pig"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"14"
		"AttackDamageMax"			"16"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"9"
		"BountyGoldMin"				"8"	
		"BountyGoldMax"				"11"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"220"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"130"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}

	"npc_classic_big_pig"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/props_gameplay/pig.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn_pig"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"22"
		"AttackDamageMax"			"24"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"15"
		"BountyGoldMin"				"15"	
		"BountyGoldMax"				"18"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"185"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"200"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}

	"npc_classic_sheep"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/hex/sheep_hex/sheep_hex.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn_sheep"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"14"
		"AttackDamageMax"			"16"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"9"
		"BountyGoldMin"				"8"	
		"BountyGoldMax"				"11"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"220"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"130"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}

	"npc_classic_big_sheep"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/hex/sheep_hex/sheep_hex.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn_sheep"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"22"
		"AttackDamageMax"			"24"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"15"
		"BountyGoldMin"				"15"	
		"BountyGoldMax"				"18"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"185"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"200"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}


	"npc_classic_half_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion_torso.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					"respawn_half_zombie"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"8"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"82"
		"AttackDamageMax"			"92"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"40"
		"BountyGoldMin"				"35"	
		"BountyGoldMax"				"40"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"170"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"550"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}

	"npc_classic_big_half_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion_torso.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"1"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					"respawn_half_zombie"

		// Armor
		//----------------------------------------------------------------
			"ArmorPhysical"				"12"
		"MagicalResistance"         "35"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"124"
		"AttackDamageMax"			"134"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"60"
		"BountyGoldMin"				"60"	
		"BountyGoldMax"				"75"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"170"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"890"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"


		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}


		"npc_classic_chicken"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/hex/fish_hex/fish_hex.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"3"
		"ModelScale" 				"1"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn_fish"
		"Ability3"					"slark_pounce"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"8"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"82"
		"AttackDamageMax"			"92"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"40"
		"BountyGoldMin"				"30"	
		"BountyGoldMax"				"35"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"255"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"485"
		"StatusHealthRegen"			"5"
		"StatusMana"				"200"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
			"OffensiveAbilities"
			{
				"Ability3"
				{
					"Name"					"slark_pounce"										
				}
				
			}
			
 
		}
	}
	
			"npc_stronger_chicken"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/hex/fish_hex_retro/fish_hex_retro.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"4"
		"ModelScale" 				"1.15"
		"UseNeutralCreepBehavior"	"1"
		"HasInventory"				"1"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn_fish"
		"Ability3"					"slark_pounce"	
		"Ability4"					""
		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"12"
		"MagicalResistance"         "35"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"124"
		"AttackDamageMax"			"134"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"60"
		"BountyGoldMin"				"55"	
		"BountyGoldMax"				"60"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"705"
		"StatusHealthRegen"			"5"
		"StatusMana"				"350"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
						"OffensiveAbilities"
			{
				"Ability3"
				{
					"Name"					"slark_pounce"										
				}
				
			}
			
						"EquippedItems"
			{
				"1"            	{"Item"        "item_orb_of_venom"}
 

			}
		}
	}
 

 

	"npc_classic_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.2"
				"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					"respawn_zombie"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"16"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"185"
		"AttackDamageMax"			"205"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"105"
		"BountyGoldMin"				"95"	
		"BountyGoldMax"				"105"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"220"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1375"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}
	"npc_classic_big_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"9"
		"ModelScale" 				"1.6"
		"UseNeutralCreepBehavior"	"1"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					""
		"Ability3"					"zombie_poison_sting_big"	
		"Ability4"					"respawn_zombie"    
		"Ability5"					"ghoul_crazy_look"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"24"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"255"
		"AttackDamageMax"			"270"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"155"
		"BountyGoldMin"				"135"	
		"BountyGoldMax"				"145"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1750"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}


	"npc_classic_necr"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/necrolyte/necrolyte.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Necrolyte"
		"GameSoundsFile"			"soundevents/game_sounds_necrolyte.vsndevts"
		"Level"						"9"
		"ModelScale" 				"1.0"
		"UseNeutralCreepBehavior"	"1"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"necrolyte_death_pulse"
		"Ability2"					""
		"Ability3"					""
		"Ability4"					"necrolyte_heartstopper_aura_2"	   
		"Ability5"					"respawn_necr"
		"Ability6"					"ghoul_crazy_look"
 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"18"
		"MagicalResistance"         "35"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"120"
		"AttackDamageMax"			"140"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"550"
		"ProjectileModel"			"particles/econ/items/necrolyte/necrophos_sullen_gold/necro_sullen_pulse_enemy_gold.vpcf"
		"ProjectileSpeed"			"600"			// Speed of projectile.		

	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"175"
		"BountyGoldMin"				"140"	
		"BountyGoldMax"				"155"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"170"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1125"
		"StatusHealthRegen"			"30.0"
		"StatusMana"				"800"	
		"StatusManaRegen"			"20.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "7427" }
					"Wearable1" { "ItemDef" "8043" }
					"Wearable1" { "ItemDef" "8044" }
					"Wearable1" { "ItemDef" "8045" }
 				
				}
				
							"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"necrolyte_death_pulse"										
				}
				
			}
		}
	}


	"npc_classic_big_necr"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/necrolyte/necrolyte.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Necrolyte"
		"GameSoundsFile"			"soundevents/game_sounds_necrolyte.vsndevts"
		"Level"						"9"
		"ModelScale" 				"1.25"
		"UseNeutralCreepBehavior"	"1"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"necrolyte_death_pulse_big"
		"Ability2"					""
		"Ability3"					""
		"Ability4"					"necrolyte_heartstopper_aura_big"	   
		"Ability5"					"respawn_necr"
		"Ability6"					"ghoul_crazy_look"
 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"26"
		"MagicalResistance"         "40"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"165"
		"AttackDamageMax"			"190"
		"AttackRate"				"1.77"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"550"
		"ProjectileModel"			"particles/econ/items/necrolyte/necrophos_sullen_gold/necro_sullen_pulse_enemy_gold.vpcf"
		"ProjectileSpeed"			"600"			// Speed of projectile.		

	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"225"
		"BountyGoldMin"				"180"	
		"BountyGoldMax"				"210"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"185"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1450"
		"StatusHealthRegen"			"45.0"
		"StatusMana"				"1200"	
		"StatusManaRegen"			"20.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "7427" }
					"Wearable1" { "ItemDef" "8043" }
					"Wearable1" { "ItemDef" "8044" }
					"Wearable1" { "ItemDef" "8045" }
 				
				}
				
							"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"necrolyte_death_pulse"										
				}
				
			}
		}
	}


	"npc_classic_pudge"	
	{
 
		"Model"						"models/heroes/pudge/pudge.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"5"
		"ModelScale" 				"1.25"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior" 	"1"
		"IsAncient"					"1"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					""  
		"Ability3"					"pudge_chakram"	
		"Ability4"					""
		"Ability5"					""
		"Ability6"					""	
		"Ability7"					"respawn_pudge"	 
		"Ability8"					"hardskin_pudge"
 	 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"25"
		"MagicalResistance"         "35"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"385"
		"AttackDamageMax"			"415"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"245"
		"BountyGoldMin"				"210"	
		"BountyGoldMax"				"235"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"325"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4500"
		"StatusHealthRegen"			"120"
		"StatusMana"				"1600"	
		"StatusManaRegen"			"5.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"



		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
					"DisableResistance"			"70.0"
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "800.0"
			    }
			}
						
			"OffensiveAbilities"
			{
				"Ability3"
				{
					"Name"					"pudge_chakram"										
				}
				
			}
			
																		"AttachWearables"
				{
					"Wearable1" { "ItemDef" "7542" }
					"Wearable1" { "ItemDef" "7547" }
					"Wearable1" { "ItemDef" "7544" }
 					"Wearable1" { "ItemDef" "7541" }
					"Wearable1" { "ItemDef" "7543" }  
 					"Wearable1" { "ItemDef" "7341" }  
 					"Wearable1" { "ItemDef" "7174" }  				
				}
 
		}
	}


	"npc_classic_big_pudge"	
	{

		"vscripts"		"ai/ai_neutral_autocast.lua"
		"Model"						"models/heroes/pudge/pudge.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"5"
		"ModelScale" 				"2"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior" 	"0"		
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					""  
		"Ability3"					"pudge_meat_hook_2"	
		"Ability4"					""
		"Ability5"					"pudge_rot_passive_2"
		"Ability6"					"pudge_dismember_2"	
		"Ability7"					"respawn_pudge"	 
		"Ability8"					"hardskin_pudge"
 	 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"32"
		"MagicalResistance"         "40"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"535"
		"AttackDamageMax"			"555"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"315"
		"BountyGoldMin"				"260"	
		"BountyGoldMax"				"320"	
	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"350"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"5250"
		"StatusHealthRegen"			"150"
		"StatusMana"				"1250"	
		"StatusManaRegen"			"15.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"



		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
							"DisableResistance"			"70.0"
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
												"AttachWearables"
				{
					"Wearable1" { "ItemDef" "7742" }
					"Wearable1" { "ItemDef" "6825" }
					"Wearable1" { "ItemDef" "6226" }
 					"Wearable1" { "ItemDef" "5049" }
					"Wearable1" { "ItemDef" "7166" }
					"Wearable1" { "ItemDef" "6115" }
					"Wearable1" { "ItemDef" "7369" }
 				
				}
								"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance"}
				"2"            	{"Item"        "item_shivas_guard"}

			}
		}
	}



	"npc_classic_grim"	
	{
	        "vscripts"        "ai/ai_grim.lua"
 
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"5"
		"ModelScale" 				"1.2"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior" 	"0"
		"IsAncient"					"1"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					""  
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					"grim_health"
		"Ability6"					""	
		"Ability7"					"respawn_grim"	 
		"Ability8"					"hardskin_pudge"
 	 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"25"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"485"
		"AttackDamageMax"			"545"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"0"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"255"
		"BountyGoldMin"				"215"	
		"BountyGoldMax"				"225"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"350"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2850"
		"StatusHealthRegen"			"150"
		"StatusMana"				"800"	
		"StatusManaRegen"			"2.5"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"



		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
					"DisableResistance"			"70.0"
 
 		"AttachWearables"//Trappings of the Ravenous Fiend
		{
		"Wearable1" {"ItemDef" "6260"}//head("Horned Visage of the Ravenous Fiend")
		"Wearable2" {"ItemDef" "6261"}//arms("Claws of the Ravenous Fiend")
		"Wearable3" {"ItemDef" "6262"}//belt("Belt of the Ravenous Fiend")
		"Wearable4" {"ItemDef" "6263"}//back("Ragged Shoulders of the Ravenous Fiend")
		}

 
		}
	}

	"npc_classic_big_grim"	
	{
	        "vscripts"        "ai/ai_big_grim.lua"
 
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"5"
		"ModelScale" 				"1.5"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior" 	"0"
		"IsAncient"					"1"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					""  
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					"grim_big_health"
		"Ability6"					""	
		"Ability7"					"respawn_grim"	 
		"Ability8"					"hardskin_pudge"
 	 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"32"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"595"
		"AttackDamageMax"			"615"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"315"
		"BountyGoldMin"				"250"	
		"BountyGoldMax"				"260"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"350"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"3850"
		"StatusHealthRegen"			"225"
		"StatusMana"				"1200"	
		"StatusManaRegen"			"7.5"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"



		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
					"DisableResistance"			"70.0"
 
 		"AttachWearables"//Trappings of the Ravenous Fiend
		{
		"Wearable1" {"ItemDef" "6260"}//head("Horned Visage of the Ravenous Fiend")
		"Wearable2" {"ItemDef" "6261"}//arms("Claws of the Ravenous Fiend")
		"Wearable3" {"ItemDef" "6262"}//belt("Belt of the Ravenous Fiend")
		"Wearable4" {"ItemDef" "6263"}//back("Ragged Shoulders of the Ravenous Fiend")
		}

 
		}
	}

 
	
	"npc_classic_skelet"	
	{
		// General
		//----------------------------------------------------------------
 
		"Model"						"models/items/wraith_king/wk_ti8_creep/wk_ti8_creep_golden.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"5"
		"ModelScale" 				"1.4"
		"UseNeutralCreepBehavior" 	"1"
		"HasInventory"				"1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn_skelet"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					""    
		"Ability6"					"ghoul_crazy_look"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"60"
		"MagicalResistance"         "50"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"695"
		"AttackDamageMax"			"710"
		"AttackRate"				"1.3"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"190"
		"BountyGoldMin"				"195"	
		"BountyGoldMax"				"215"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"425"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4150"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"700"
		"VisionNighttimeRange"		"700"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
 
			    }
			}
									"EquippedItems"
			{
				"1"            	{"Item"        "item_hyperstone"}
				"2"            	{"Item"        "item_basher_skelet"}
				"3"            	{"Item"        "item_desolator"}				 

			}
		}
	}

	"npc_classic_big_skelet"	
	{
		// General
		//----------------------------------------------------------------
 
		"Model"						"models/items/wraith_king/wk_ti8_creep/wk_ti8_creep_golden.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"5"
		"ModelScale" 				"1.7"
		"UseNeutralCreepBehavior" 	"1"
		"HasInventory"				"1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn_skelet"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					""    
		"Ability6"					"ghoul_crazy_look"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"80"
		"MagicalResistance"         "55"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"915"
		"AttackDamageMax"			"950"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"280"
		"BountyGoldMin"				"280"	
		"BountyGoldMax"				"300"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"475"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"6150"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"700"
		"VisionNighttimeRange"		"700"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
 
			    }
			}
									"EquippedItems"
			{
				"1"            	{"Item"        "item_hyperstone"}
				"2"            	{"Item"        "item_basher_skelet"}
				"3"            	{"Item"        "item_desolator"}				 

			}
		}
	}


	
		"npc_classic_skeleton_king"	
	{
		// General
		//----------------------------------------------------------------
        "vscripts"        "ai/ai_skelet_king.lua"
		"UseNeutralCreepBehavior" 	"0"
		"Model"						"models/heroes/wraith_king/wraith_king.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_SkeletonKing"
		"GameSoundsFile"			"soundevents/game_sounds_skeletonking.vsndevts"
		"Level"						"7"
		"ModelScale" 				"1.5"
		"HasInventory"				"1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn_skelet_2"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					"spawnlord_aura"
		"Ability6"					"skeleton_king_mortal_strike"
		"Ability7"					"ghoul_crazy_look"
		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"20"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"645"
		"AttackDamageMax"			"715"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"335"
		"BountyGoldMin"				"250"	
		"BountyGoldMax"				"275"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"425"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"3550"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DisableResistance"			"45.0"

 
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
 		"AttachWearables"//Trappings of the Ravenous Fiend
		{
		"Wearable1" {"ItemDef" "9747"}//head("Horned Visage of the Ravenous Fiend")
		"Wearable2" {"ItemDef" "7105"}//arms("Claws of the Ravenous Fiend")
		"Wearable3" {"ItemDef" "7103"}//belt("Belt of the Ravenous Fiend")
	 
		"Wearable4" {"ItemDef" "7107"}//back("Ragged Shoulders of the Ravenous Fiend")
		"Wearable5" {"ItemDef" "7104"}//back("Ragged Shoulders of the Ravenous Fiend")
		"Wearable5" {"ItemDef" "148"}//back("Ragged Shoulders of the Ravenous Fiend")
		  

		 
		}
 
 	 
						"EquippedItems"
			{
				"1"            	{"Item"        "item_satanic"}
 				"2"            	{"Item"        "item_assault"}
				"3"            	{"Item"        "item_hyperstone"}
				"4"            	{"Item"        "item_hyperstone"}
			}
			
		}
	}
	


		"npc_classic_big_skeleton_king"	
	{
		// General
		//----------------------------------------------------------------
        "vscripts"        "ai/ai_skelet_king.lua"
		"UseNeutralCreepBehavior" 	"0"
		"Model"						"models/heroes/wraith_king/wraith_king.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_SkeletonKing"
		"GameSoundsFile"			"soundevents/game_sounds_skeletonking.vsndevts"
		"Level"						"7"
		"ModelScale" 				"1.8"
		"HasInventory"				"1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn_skelet_2"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					"spawnlord_aura"
		"Ability6"					"skeleton_king_mortal_strike"
		"Ability7"					"ghoul_crazy_look"
		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"35"
		"MagicalResistance"         "30"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1100"
		"AttackDamageMax"			"1150"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"450"
		"BountyGoldMin"				"350"	
		"BountyGoldMax"				"375"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"475"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4600"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1100"
		"VisionNighttimeRange"		"1100"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DisableResistance"			"45.0"

 
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
 		"AttachWearables"//Trappings of the Ravenous Fiend
		{
		"Wearable1" {"ItemDef" "9747"}//head("Horned Visage of the Ravenous Fiend")
		"Wearable2" {"ItemDef" "7105"}//arms("Claws of the Ravenous Fiend")
		"Wearable3" {"ItemDef" "7103"}//belt("Belt of the Ravenous Fiend")
	 
		"Wearable4" {"ItemDef" "7107"}//back("Ragged Shoulders of the Ravenous Fiend")
		"Wearable5" {"ItemDef" "7104"}//back("Ragged Shoulders of the Ravenous Fiend")
		"Wearable5" {"ItemDef" "148"}//back("Ragged Shoulders of the Ravenous Fiend")
		  

		 
		}
 
 	 
						"EquippedItems"
			{
				"1"            	{"Item"        "item_satanic"}
 				"2"            	{"Item"        "item_assault"}
				"3"            	{"Item"        "item_hyperstone"}
				"4"            	{"Item"        "item_hyperstone"}
			}
			
		}
	}
	

  
	
 

 

	"npc_classic_wave_big_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.5"
        "BoundsHullName"         "DOTA_HULL_SIZE_SMALL"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					""
		"Ability3"					"zombie_passive"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"9"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"108"
		"AttackDamageMax"			"112"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"32"
		"BountyGoldMin"				"4"	
		"BountyGoldMax"				"6"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1500"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}
  
 


	"npc_classic_ghoul"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"ghoul_devourer"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					"respawn_strong"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"14"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"370"
		"AttackDamageMax"			"370"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"150"
		"BountyGoldMin"				"60"	
		"BountyGoldMax"				"120"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"270"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"500"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}

	"npc_classic_wave_ghoul"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"ghoul_devourer"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"                  "zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"14"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"375"
		"AttackDamageMax"			"425"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"125"
		"BountyGoldMin"				"16"	
		"BountyGoldMax"				"20"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1800"
		"StatusHealthRegen"			"30.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}

	"npc_classic_wave_pudge"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/pudge/pudge.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"4"
		"ModelScale" 				"0.8"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"zombie_passive"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"		            "pudge_dismember_wave"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"20"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"620"
		"AttackDamageMax"			"635"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"150"
		"BountyGoldMin"				"18"	
		"BountyGoldMax"				"24"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"3650"
		"StatusHealthRegen"			"100.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
				
											"OffensiveAbilities"
			{
				"Ability5"
				{
					"Name"					"pudge_dismember_wave"										
				}
				
			}
						"AttachWearables"
				{
					"Wearable1" { "ItemDef" "14033" }
					"Wearable1" { "ItemDef" "14036" }
					"Wearable1" { "ItemDef" "14035" }
					"Wearable1" { "ItemDef" "14039" }
					"Wearable1" { "ItemDef" "14034" }
					"Wearable1" { "ItemDef" "14038" }
					"Wearable1" { "ItemDef" "14037" }
 				
				}
		}
	}
	
 

	 

	"npc_classic_witch"	
	{
		// General
		//----------------------------------------------------------------
       		"vscripts"		"ai/ai_boss_ghost.lua"
		"Model"						"models/heroes/death_prophet/death_prophet.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"15"
		"ModelScale" 				"1.2"
		"CanBeDominated"            "0"		
		"UseNeutralCreepBehavior"	"0"
		"IsAncient"					"1"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_boss_magick_attack"
		"Ability2"					"witch_voodoo"   
		"Ability3"					"witch_death_aura"	
		"Ability4"					"witch_cursed_crown"
		"Ability5"					"doom_doom_lua"
		 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"15"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.25"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "700"
	    "AttackRange"           	"700"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"1425"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"210"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"5250"
		"StatusHealthRegen"			"30"	
		"StatusMana"				"1000"
		"StatusManaRegen"			"20.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"700"	
		"VisionNighttimeRange"		"700"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{

			"AttachWearables"
			{
		"Wearable1" {"ItemDef" "6846"}//belt("Mourning Mother's Scarf")
		"Wearable2" {"ItemDef" "6843"}//legs("Mourning Mother's Dress")
		"Wearable3" {"ItemDef" "6844"}//armor("Mourning Mother's Top")
		"Wearable4" {"ItemDef" "6845"}//head("Mourning Mother's Veil")
		"Wearable5" {"ItemDef" "6875"}//ability_ultimate("Spirits of the Mourning Mother")
			}
 
		}
	}	


	"npc_boss_mutant"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_flesh_golem.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"25"
		"ModelScale" 				"1.5"
		"CanBeDominated"            "0"		
		"UseNeutralCreepBehavior"	"1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"mutant_dismemberment"
		"Ability3"					"mutant_reflector"	
		"Ability4"					""
		"Ability5"					""
		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"25"
		"MagicalResistance"         "35"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"200"
		"AttackDamageMax"			"400"
		"AttackRate"				"1.0"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"700"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"2230"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"270"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"12500"
		"StatusHealthRegen"			"150.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"700"
		"VisionNighttimeRange"		"700"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}
 
 		"npc_tombstone1"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/heroes/undying/undying_tower.vmdl" 
	"SoundSet"					"Undying_Tombstone"					// Name of sound set.
       "IsAncient"                  "1"
		"wearable"				"8630" 
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"zombie_tombstone"			// Ability 1.
		"Ability2"					"pudge_rot_tomb_1"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
 
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}

 		"npc_tombstone2"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/heroes/undying/undying_tower.vmdl" 
	"SoundSet"					"Undying_Tombstone"						// Name of sound set.
        "IsAncient"                  "1"
		"wearable"				"8630"		
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"zombie_tombstone"			// Ability 1.
		"Ability2"					"pudge_rot_tomb_2"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"			// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}
	

 		"npc_tombstone3"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/heroes/undying/undying_tower.vmdl" 
	"SoundSet"					"Undying_Tombstone"					// Name of sound set.
        "IsAncient"                  "1"
				"wearable"				"8630"
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"zombie_tombstone"			// Ability 1.
		"Ability2"					"pudge_rot_tomb_3"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"		// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
 
	}
	

 		"npc_tombstone4"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/heroes/undying/undying_tower.vmdl" 
	"SoundSet"					"Undying_Tombstone"					// Name of sound set.
        "IsAncient"                  "1"
				"wearable"				"8630"
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"zombie_tombstone"			// Ability 1.
		"Ability2"					"pudge_rot_tomb_4"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"		// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}
 
	
	 		"npc_tombstone_flash_3"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/items/undying/idol_of_ruination/idol_tower_gold_sim.vmdl" 
	"SoundSet"					"Undying_Tombstone"						// Name of sound set.
        "IsAncient"                  "1"
			"wearable"				"8630"	
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"zombie_tombstone"			// Ability 1.
		"Ability2"					"nevermore_dark_lord_2"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"			// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}
	
	 		"npc_tombstone_flash_4"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/items/undying/idol_of_ruination/idol_tower_sim.vmdl" 
	"SoundSet"					"Undying_Tombstone"						// Name of sound set.
        "IsAncient"                  "1"
			"wearable"				"8630"	
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"zombie_tombstone"			// Ability 1.
		"Ability2"					"abyssal_underlord_atrophy_aura_2"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"			// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}

	"npc_boss_ghost"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/neutral_creeps/n_creep_ghost_a/n_creep_ghost_a.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.5"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_magick_attack"
		"Ability2"					"ghost_elusive"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"25"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "5000"
	    "AttackRange"           	"350"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"30"
		"BountyGoldMin"				"10"	
		"BountyGoldMax"				"30"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"300"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"250"
		"StatusHealthRegen"			"0.5"	
		"StatusMana"				"0"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"	
		"VisionNighttimeRange"		"5000"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}	


	"npc_boss_ghoul"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				"2.0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"ghoul_devourer"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"40"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"370"
		"AttackDamageMax"			"370"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"60"
		"BountyGoldMin"				"20"	
		"BountyGoldMax"				"60"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"400"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}


 
//------Halloween---------


 		"npc_tombstone_clock"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/items/rattletrap/the_neuromaniac_experiment_subject_no08/the_neuromaniac_experiment_subject_no08.vmdl" 
	"SoundSet"					"Undying_Tombstone"					// Name of sound set.
        "IsAncient"                  "1"
				"wearable"				"8630"
		"ModelScale"				"2.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"golden_mine_passive_5"			// Ability 1.
		"Ability2"					"pudge_rot_tomb_clock"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"		// Hull type used for navigation/locomotion.
		"RingRadius"				"80"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}	
 

	"npc_undying_clock"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undying.lua"
		"Model"						"models/heroes/rattletrap/rattletrap.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.45"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_clock"
		"Ability2"					"ghoul_crazy_look"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"		"zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"85"
		"MagicalResistance"         "60"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1450"
		"AttackDamageMax"			"1475"
		"AttackRate"				"2.3"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"180"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"860"
		"BountyGoldMin"				"620"	
		"BountyGoldMax"				"850"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"12500"
		"StatusHealthRegen"			"45"
		"StatusMana"				"350"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "17951" }  
					"Wearable1" { "ItemDef" "17952" }
 					"Wearable1" { "ItemDef" "17953" }
 				
				}
					"DisableResistance"			"35.0"
 
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_hyperstone"}
			}	 	
			
		}
	}
	
	

	"npc_classic_wave_golem"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/lane_creeps/creep_radiant_hulk/creep_radiant_diretide_ancient_hulk.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Roshan"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"12"
		"ModelScale" 				"1.25"
		"HasInventory"				"1"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"zombie_passive"
		"Ability3"					"haloween_golem_flaming_fists"	
		"Ability4"					""
		"Ability5"		            ""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"85"
		"MagicalResistance"         "60"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1065"
		"AttackDamageMax"			"1110"
		"AttackRate"				"1.65"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"155"
		"BountyGoldMin"				"23"	
		"BountyGoldMax"				"26"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"5850"
		"StatusHealthRegen"			"50.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
					"DisableResistance"			"35.0"
 
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_hyperstone"}

 

			}	
 
		}
	}

	"npc_classic_wave_fire_golem"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/ai_fire_golem.lua"
		"Model"						"models/creeps/lane_creeps/creep_dire_hulk/creep_dire_diretide_ancient_hulk.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Roshan"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"12"
		"UseNeutralCreepBehavior"	"0"
		"ModelScale" 				"1.6"
		"HasInventory"				"1"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"golem_fireball"
		"Ability3"					"haloween_golem_flaming_fists"	
		"Ability4"					""
		"Ability5"		            "zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"90"
		"MagicalResistance"         "60"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1465"
		"AttackDamageMax"			"1515"
		"AttackRate"				"1.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"155"
		"BountyGoldMin"				"23"	
		"BountyGoldMax"				"26"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"8550"
		"StatusHealthRegen"			"50.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
					"DisableResistance"			"35.0"
 
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_gloves"}
				"2"            	{"Item"        "item_gloves"}

			}	
 
		}
	}


	"npc_classic_wave_fly_pudge"	
	{
		// General
		//----------------------------------------------------------------
    		"vscripts"                  "ai/boss_wave/ai_fly_pudge.lua"
    				"UseNeutralCreepBehavior" 	"0"
		"Model"						"models/heroes/pudge/pudge.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Pudge"
		"GameSoundsFile"			"soundevents/game_sounds_pudge.vsndevts"
		"Level"						"1"
		"ModelScale" 				"0.9"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"pudge_meat_hook_fly"
		"Ability2"					"ghost_elusive_3"
		"Ability3"					"range_magick_attack_4"	  
		"Ability4"					"ghoul_crazy_look"
        "Ability5"                   "zombie_passive"
		"Ability6"					"ghost_speed"
 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"47"
		"MagicalResistance"         "55"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.8"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "5000"
	    "AttackRange"           	"350"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"125"
		"BountyGoldMin"				"26"	
		"BountyGoldMax"				"29"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"75"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"5250"
		"StatusHealthRegen"			"0.0"	
		"StatusMana"				"750"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"	
		"VisionNighttimeRange"		"900"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
						"AttachWearables"
				{
					"Wearable1" { "ItemDef" "18063" }
					"Wearable1" { "ItemDef" "18064" }
					"Wearable1" { "ItemDef" "18065" }
					"Wearable1" { "ItemDef" "18066" }
					"Wearable1" { "ItemDef" "18067" }
					"Wearable1" { "ItemDef" "18068" }
					"Wearable1" { "ItemDef" "18069" } 	  		
				}
					"DisableResistance"			"35.0"
 
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_hyperstone"}
 
 

			}	
		}
	}

	"npc_skelet_boss"	
	{
		// General
		//----------------------------------------------------------------
		
 		"vscripts"                  "ai/ai_skelet_boss.lua"
		
		"Model"						"models/items/wraith_king/arcana/wraith_king_arcana.vmdl"	// Model.
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_SkeletonKing"
		"GameSoundsFile"			"soundevents/game_sounds_skeletonking.vsndevts"
		"Level"						"25"
		"ModelScale" 				"1.7"
		"ConsideredHero"			"1"
		"IsAncient"					"1"
		"IsBossMonster"				"1"	
		"UseNeutralCreepBehavior" 	"0"
 
		"HasInventory"              "1"
		
		"MinimapIcon"				"minimap_roshancamp"
		"MinimapIconSize"			"950"

		// Abilities
		//----------------------------------------------------------------
   	"Ability1"					""		
 		"Ability2"					"skeleton_king_hellfire_blast_boss"
 		"Ability3"					"skeleton_king_vampiric_aura_boss"
 		"Ability4"					"skeleton_king_mortal_strike_boss"
	 	"Ability5"					"skeleton_king_reincarnation_boss"
 		"Ability6"					"skelet_mini"
 		"Ability7"					""				
 		"Ability8"					"ghoul_crazy_look"	
 	"Ability9"                  "boss_thirst"
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"105"			// Physical protection.
		"MagicalResistance"         "58"
		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"1910"					
		"AttackDamageMax"			"1940"	
		"AttackDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.5"				// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"800"	
		"AttackRange"				"120"
  
		"MovementSpeedActivityModifiers"
		{
			"walk"		"0"
			"run"		"345"
			"run_fast"	"373"
		}
		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"90"
		"HealthBarOffset"			"495"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"500"		// Experience earn.
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"		// Speed.	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1000000"		// Base health.
		"StatusHealthRegen"			"150.0"		// Health regeneration rate.
		"StatusMana"				"20000"			// Base mana.
		"StatusManaRegen"			"50.0"		// Mana regeneration rate.		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1000"		// Range of vision during day light.
		"VisionNighttimeRange"		"1000"		// Range of vision at night time.


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"						// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
		

 
			
			"DisableResistance"			"65.0"
 

			"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance_christmas_boss"}
				"2"            	{"Item"        "item_shivas_guard_christmas_boss"}
				"3"            	{"Item"        "item_assault_christmas_boss"}  
				"4"            	{"Item"        "item_sange_last"}

			}				
 
			 			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "13456" }
					"Wearable1" { "ItemDef" "13473" }
					"Wearable1" { "ItemDef" "13569" }
					"Wearable1" { "ItemDef" "13571" }
					"Wearable1" { "ItemDef" "13743" }
					"Wearable1" { "ItemDef" "13760" }
  				
				}		
 
		}
	}

	"npc_skelet_boss_mini"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/wraith_king/wk_ti8_creep/wk_ti8_creep_crimson.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_SkeletonKing"
		"GameSoundsFile"			"soundevents/game_sounds_skeletonking.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.2"
		"HasInventory"              "1"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					""
		"Ability3"					"skelet_fury_swipes"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"45"
		"MagicalResistance"         "55"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"125"
		"AttackDamageMax"			"135"
		"AttackRate"				"1.35"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"107"
		"BountyGoldMin"				"16"	
		"BountyGoldMax"				"20"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"750"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"7150"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 
 			"EquippedItems"
			{
				"1"            	{"Item"        "item_moon_shard"}
				"2"            	{"Item"        "item_moon_shard"}
				"3"            	{"Item"        "item_moon_shard"}  
 

			}
		}
	}  
//------Christmas---------
	"npc_christmas_boss"	
	{
		// General
		//----------------------------------------------------------------
		
 		"vscripts"                  "ai/ai_christmas_boss.lua"
		
		"Model"						"models/heroes/doom/doom.vmdl"	// Model.
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Roshan"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"25"
		"ModelScale" 				"1.7"
		"ConsideredHero"			"1"
		"IsAncient"					"1"
		"IsBossMonster"				"1"	
		"UseNeutralCreepBehavior" 	"0"
 
		"HasInventory"              "1"
		
		"MinimapIcon"				"minimap_roshancamp"
		"MinimapIconSize"			"950"

		// Abilities
		//----------------------------------------------------------------
   	"Ability1"					"doom_bringer_infernal_blade"		
 		"Ability2"					"doom_doom_lua"
 		"Ability3"					"boss_blink_strike"
 		"Ability4"					"ghoul_crazy_look"
	 	"Ability5"					"doom_devour_lua"
 		"Ability6"					""
 		"Ability7"					"doom_mini"				
 		"Ability8"					"blood"	
 	"Ability9"                  "boss_thirst"
 	"Ability10"                  "phantom_assassin_phantom_strike_lua"
 	"Ability11"                  ""
  	"Ability12"    	                                 "christmas_boss_music"
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"158"			// Physical protection.
		"MagicalResistance"         "95"
		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2850"					
		"AttackDamageMax"			"3250"	
		"AttackDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AttackRate"				"1.3"
		"AttackAnimationPoint"		"0.5"				// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"800"	
		"AttackRange"				"120"
  

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"90"
		"HealthBarOffset"			"495"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"500"		// Experience earn.
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"		// Speed.	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"125000"		// Base health.
		"StatusHealthRegen"			"150.0"		// Health regeneration rate.
		"StatusMana"				"20000"			// Base mana.
		"StatusManaRegen"			"50.0"		// Mana regeneration rate.		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1000"		// Range of vision during day light.
		"VisionNighttimeRange"		"1000"		// Range of vision at night time.


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"						// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
		

 
			
			"DisableResistance"			"95.0"
 			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "6102" }
					"Wearable1" { "ItemDef" "17985" }
					"Wearable1" { "ItemDef" "17987" }
					"Wearable1" { "ItemDef" "17988" }
					"Wearable1" { "ItemDef" "17986" }
					"Wearable1" { "ItemDef" "6506" }
					"Wearable1" { "ItemDef" "9741" }
 				
				}

			"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance_christmas_boss"}
				"2"            	{"Item"        "item_shivas_guard_christmas_boss"}
				"3"            	{"Item"        "item_assault_christmas_boss"}  
				"4"            	{"Item"        "item_sange_last"}

			}				
 
		
 
		}
	}
	
	
	"npc_classic_mini_crampus"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/doom/doom.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"1"
		"ModelScale" 				"0.3"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"doom_bringer_infernal_blade_mini"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"60"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1150"
		"AttackDamageMax"			"1250"
		"AttackRate"				"0.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"107"
		"BountyGoldMin"				"16"	
		"BountyGoldMax"				"20"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"750"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"6550"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 
			 			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "8502" }
					"Wearable1" { "ItemDef" "8507" }
					"Wearable1" { "ItemDef" "8504" }
					"Wearable1" { "ItemDef" "8508" }
					"Wearable1" { "ItemDef" "8505" }
					"Wearable1" { "ItemDef" "8506" }
					"Wearable1" { "ItemDef" "8503" }
 				
				}
									"OffensiveAbilities"
			{
				"Ability2"
				{
					"Name"					"doom_bringer_infernal_blade_mini"										
				}
				
			}
		}
	}

	"npc_classic_doom_crampus"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/warlock/golem/ahmhedoq/ahmhedoq.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.2"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"doom_aura"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"65"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"2340"
		"AttackDamageMax"			"2628"
		"AttackRate"				"0.75"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"107"
		"BountyGoldMin"				"16"	
		"BountyGoldMax"				"20"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"750"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"18680"
		"StatusHealthRegen"			"150.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 
 
 
		}
	}

"npc_greevil"
{
// General
//--------------------------------------------------------------—
 		"vscripts"                  "ai/ai_greevil.lua"
 		
"BaseClass" "npc_dota_creature"
"Model" "models/courier/greevil/gold_greevil.vmdl"
"ModelScale" "3.5"
"Level" "10"
"HealthBarOffset" "140"
"HasInventory" "0"
 
		"IsAncient"					"1"
		"IsBossMonster"				"1"	
"UseNeutralCreepBehavior" "0"


// Abilities
//--------------------------------------------------------------—
"Ability1" "greevil"
"Ability2" ""
"Ability3" ""
"Ability4" ""


// Armor
//--------------------------------------------------------------—
"ArmorPhysical" "0"
"MagicalResistance" "0"

// Attack
//--------------------------------------------------------------—
"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
"AttackDamageMin" "0"
"AttackDamageMax" "0"

// Bounty
//--------------------------------------------------------------—
"BountyGoldMin" "0.0"
"BountyGoldMax" "0.0"

// Bounds
//--------------------------------------------------------------—
"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
"RingRadius" "30"
"CollisionSize" "1"


// Movement
//--------------------------------------------------------------—
"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
"MovementSpeed" "550"

// Status
//--------------------------------------------------------------—
"StatusHealth" "1000000000"
"StatusHealthRegen" "10000"
"StatusMana" "0"
"StatusManaRegen" "0"

// Vision
//--------------------------------------------------------------—
"VisionDaytimeRange" "900"
"VisionNighttimeRange" "900"

// Team
//--------------------------------------------------------------—
"TeamName" "DOTA_TEAM_BADGUYS"
"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
"UnitRelationshipClass" "DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

	}

		"npc_classic_new_years"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/ice_biome/frostbitten/n_creep_frostbitten_swollen01.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"4"
		"ModelScale" 				"0.8"
 
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"frozen_zombie_attack"
		"Ability2"					"ghoul_crazy_look"  
		"Ability3"					"zombie_passive"	
		"Ability4"					""
		"Ability5"		            ""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"25"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"920"
		"AttackDamageMax"			"950"
		"AttackRate"				"1.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
        "BaseAttackSpeed"			"160"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"180"
		"BountyGoldMin"				"36"	
		"BountyGoldMax"				"42"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"3500"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
 
		}
	}

		"npc_classic_new_years_lich"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/lich/lich.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_magick_attack_4"
		"Ability2"					"ghost_elusive_3"
		"Ability3"					"zombie_passive"	
		"Ability4"					"lich_chain_frost"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"30"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.3"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "5000"
	    "AttackRange"           	"350"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"155"
		"BountyGoldMin"				"150"	
		"BountyGoldMax"				"155"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"300"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4350"
		"StatusHealthRegen"			"0.0"	
		"StatusMana"				"2000"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"	
		"VisionNighttimeRange"		"900"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}

														"OffensiveAbilities"
			{
				"Ability5"
				{
					"Name"					"lich_chain_frost"											
				}				
			}

						"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9756" }
					"Wearable1" { "ItemDef" "14998" }
					"Wearable1" { "ItemDef" "7576" }
				}
		}
	}

			"npc_classic_new_years_winterwyvern"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/winterwyvern/winterwyvern.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_magick_attack_5"
		"Ability2"					"ghost_elusive_3"
		"Ability3"					"zombie_passive"	
		"Ability4"					"winter_wyvern_winters_curse"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"35"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.5"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "5000"
	    "AttackRange"           	"350"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"155"
		"BountyGoldMin"				"200"	
		"BountyGoldMax"				"215"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"300"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4250"
		"StatusHealthRegen"			"0.0"	
		"StatusMana"				"3500"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"	
		"VisionNighttimeRange"		"900"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}

														"OffensiveAbilities"
			{
				"Ability4"
				{
					"Name"					"winter_wyvern_winters_curse"											
				}				
			}

						"AttachWearables"
				{
					"Wearable1" { "ItemDef" "8017" }
					"Wearable1" { "ItemDef" "7292" }
				}
		}
	}	


		"npc_classic_new_years_ancient"	
	{
		// General
		//----------------------------------------------------------------
				"vscripts"		"ai/ai_ancient.lua"

		"Model"						"models/heroes/ancient_apparition/ancient_apparition.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"0"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					"zombie_passive"
		"Ability5"		            "essence_freezing_field"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"35"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1250"
		"AttackDamageMax"			"1320"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"225"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"180"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"6150"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"1300"	
		"StatusManaRegen"			"25.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1000"
		"VisionNighttimeRange"		"1000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 
			
 

									"AttachWearables"
				{
					"Wearable1" { "ItemDef" "7462" }
					"Wearable1" { "ItemDef" "9462" }
				}
		}
	}	

	 

}
