// Units File

"DOTAUnits"
{
	"Version"	"1"
	
// Boss

 
"npc_boss_Gurd"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/warlock/warlock_fourleg_demon.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_WarlockGolem"			// Name of sound set.
		"IdleSoundLoop"				"Hero_WarlockGolem.Spawn_Loop"
		"Level"						"6"
		"ModelScale" 				"1.8"
        "BoundsHullName"         "DOTA_HULL_SIZE_HERO"

 		"ConsideredHero"			"1"
		"MinimapIcon"					"minimap_roshancamp"
		"MinimapIconSize"				"450"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"hardskin_slark"
		"Ability2"					"Gurd_summon_wolves"
		"Ability3"					""	
		"Ability4"					""
		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"30"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"540"
		"AttackDamageMax"			"560"
		"AttackRate"				"2.0"
		"AttackAnimationPoint"		"0.5"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
        "BaseAttackSpeed"			"120"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"70"
		"HealthBarOffset"			"225"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"120"
		"BountyGoldMin"				""	
		"BountyGoldMax"				""

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"475"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"18000"  
		"StatusHealthRegen"			"200"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

 
 		"Creature"
		{
 
			
			"OffensiveAbilities"
			{
				"Ability2"
				{
					"Name"					"Gurd_summon_wolves"										
				}
				
			}
			
 
		}
 
 
	}
	"npc_boss_pig"	
	{
		// General
		//----------------------------------------------------------------
 	
		"Model"						"models/items/beastmaster/boar/legacy_of_the_nords_battle_boar/legacy_of_the_nords_battle_boar.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"10"
		"ModelScale" 				"1.65"
		"UseNeutralCreepBehavior"	"1"
		"IsAncient"					"1"
		"ConsideredHero"			"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"bo_eat"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"55"
		"MagicalResistance"         "40"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"425"
		"AttackDamageMax"			"525"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"125"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"1250"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"385"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"15500"
		"StatusHealthRegen"			"25"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

 
	}
	"npc_boss_dead_pig"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/ai_boss_dead_pig.lua"		
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"15"
		"ModelScale" 				"2.5"
		"ConsideredHero"			"1"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"              "1"
		"IsAncient"					"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"dead_stealer_feast"
		"Ability2"					"pig_dead_open_wounds"
		"Ability3"					"lifestealer_passive"	
		"Ability4"					""
		"Ability5"					"aghsfort_lifestealer_enraged_pulse"
		"Ability6"					"ghoul_crazy_look"
		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"30"
		"MagicalResistance"         "55"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"895"
		"AttackDamageMax"			"950"
		"AttackRate"				"1.15"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"7230"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"17500"
		"StatusHealthRegen"			"20"
		"StatusMana"				"2500"	
		"StatusManaRegen"			"3.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"850"
		"VisionNighttimeRange"		"850"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9215" }
					"Wearable1" { "ItemDef" "13787" }
					"Wearable1" { "ItemDef" "12934" }
					"Wearable1" { "ItemDef" "6475" }
				}
				
		
 			"DisableResistance"			"80.0"
			
		"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance_dead_boss"}
				"2"            	{"Item"        "item_assault_dead_boss"}
 
			}
		}
		
	}
"npc_boss_slark"	
	{
		// General
		//----------------------------------------------------------------
       	"vscripts"		"ai/mobs/ai_boss_slark.lua"
		"Model"						"models/heroes/slark/slark.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Slark"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_slark.vsndevts"
		"Level"						"16"
		"ModelScale" 				"1.8"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"
        "BoundsHullName"         "DOTA_HULL_SIZE_HERO"

 		"ConsideredHero"			"1"
		"MinimapIcon"					"minimap_roshancamp"
		"MinimapIconSize"				"450"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"hardskin_slark"
		"Ability2"					"slark_pounce"
		"Ability3"					"slark_essence_shift_boss"	
		"Ability4"					"slark_shadow_dance_boss"
		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"110"
		"MagicalResistance"         "35"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"420"
		"AttackDamageMax"			"560"
		"AttackRate"				"1.3"
		"AttackAnimationPoint"		"0.5"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
        "BaseAttackSpeed"			"160"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"70"
		"HealthBarOffset"			"225"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"300"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"475"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"12500"  
		"StatusHealthRegen"			"125"
		"StatusMana"				"650"	
		"StatusManaRegen"			"5.5"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 		
						"EquippedItems"
			{
				"1"            	{"Item"        "item_orb_of_venom"}
				"2"            	{"Item"        "item_echo_sabre_2"}
				"3"            	{"Item"        "item_monkey_king_bar"}
			}

			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "336" }
					"Wearable1" { "ItemDef" "6421" }
					"Wearable1" { "ItemDef" "6417" }
 					"Wearable1" { "ItemDef" "5101" }
  					"Wearable1" { "ItemDef" "6420" }	 				
				}
		}
	}
	"npc_boss_slardar"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/slardar/slardar.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Slardar"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_slardar.vsndevts"
		"Level"						"12"
		"ModelScale" 				"1.8"
		"HasInventory"				"1"
        "BoundsHullName"         "DOTA_HULL_SIZE_HERO"

 		"ConsideredHero"			"1"
		"MinimapIcon"					"minimap_roshancamp"
		"MinimapIconSize"				"450"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"slardar_bash"
		"Ability2"					"slardar_slithereen_crush"
		"Ability3"					"generic_hidden"	
		"Ability4"					"generic_hidden"
		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"145"
		"MagicalResistance"         "22"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"670"
		"AttackDamageMax"			"690"
		"AttackRate"				"1.9"
		"AttackAnimationPoint"		"0.5"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
        "BaseAttackSpeed"			"160"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"70"
		"HealthBarOffset"			"225"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"300"
		"BountyGoldMin"				"555"	
		"BountyGoldMax"				"850"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"520"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"15000"
		"StatusHealthRegen"			"200"
		"StatusMana"				"650"	
		"StatusManaRegen"			"5.5"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 		
						"EquippedItems"
			{
				"1"            	{"Item"        "item_echo_sabre_2"}
				"2"            	{"Item"        "item_monkey_king_bar"}
			}

			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "336" }
					"Wearable1" { "ItemDef" "6421" }
					"Wearable1" { "ItemDef" "6417" }
 					"Wearable1" { "ItemDef" "5101" }
  					"Wearable1" { "ItemDef" "6420" }	 				
				}
				"OffensiveAbilities"
			{
				"Ability2"
				{
					"Name"					"slardar_slithereen_crush"										
				}
				
			}
			
		}	
	}
	"npc_boss_bear"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/lone_druid/bear/iron_claw_spirit_bear/iron_claw_spirit_bear.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Slardar"
		"GameSoundsFile"			"sounds/weapons/hero/lone_druid/spirit_bear_preattack01.vsnd"
		"Level"						"12"
		"ModelScale" 				"1.8"
		"HasInventory"				"1"
        "BoundsHullName"         "DOTA_HULL_SIZE_HERO"

 		"ConsideredHero"			"1"
		"MinimapIcon"					"minimap_roshancamp"
		"MinimapIconSize"				"450"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"Bear_overpower"
		"Ability2"					"bear_fury_swipes"
		"Ability3"					"generic_hidden"	
		"Ability4"					"generic_hidden"
		
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"190"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"780"
		"AttackDamageMax"			"821"
		"AttackRate"				"1.9"
		"AttackAnimationPoint"		"0.5"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
        "BaseAttackSpeed"			"160"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"70"
		"HealthBarOffset"			"225"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"500"
		"BountyGoldMin"				"650"	
		"BountyGoldMax"				"850"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"520"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"11000"
		"StatusHealthRegen"			"320"
		"StatusMana"				"650"	
		"StatusManaRegen"			"5.5"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 		
						"EquippedItems"
			{
				"1"            	{"Item"        "item_javelin"}
			}

			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "336" }
					"Wearable1" { "ItemDef" "6421" }
					"Wearable1" { "ItemDef" "6417" }
 					"Wearable1" { "ItemDef" "5101" }
  					"Wearable1" { "ItemDef" "6420" }	 				
				}
				"OffensiveAbilities"
			{
				"Ability2"
				{
					"Name"					"Bear_overpower"										
				}
				
			}
			
		}	
	}
	"npc_classic_Night_Stalker_boss"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/nightstalker/nightstalker_night.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"25"
		"ModelScale" 				"2.6"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"night_stalker_void"
		"Ability2"					"respawn"
		"Ability3"					"Stalker_dispersion"	
		"Ability4"					"Stalker_howl"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"240"
		"MagicalResistance"         "18"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1420"
		"AttackDamageMax"			"1421"
		"AttackRate"				"0.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"400"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"100"
		"BountyGoldMin"				"200"	
		"BountyGoldMax"				"250"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"375"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"14900"
		"StatusHealthRegen"			"610"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 		
						"EquippedItems"
			{
				"1"            	{"Item"        "item_desolator_2_custom"}
				"1"            	{"Item"        "item_vampire_claw"}
			}

				"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"night_stalker_void"										
				}
				"Ability2"
				{
					"Name"					"Stalker_howl"										
				}
			}
			
		}	
	}
 
	"npc_classic_half_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion_torso.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"8"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"12"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"5200"
		"AttackDamageMax"			"7400"
		"AttackRate"				"2.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"90"
		"BountyGoldMin"				"160"	
		"BountyGoldMax"				"220"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"25000"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
	}
	"npc_witch_boss_1"	
	{
		// General
		//----------------------------------------------------------------
 
		"Model"						"models/heroes/death_prophet/death_prophet.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_DeathProphet"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_death_prophet.vsndevts"
		"Level"						"8"
		"ModelScale" 				"1.2"	
		"UseNeutralCreepBehavior"	"1"
        "BoundsHullName"         "DOTA_HULL_SIZE_HERO"
		"IsConsideredBoss"						"1"

 		"ConsideredHero"			"1"
		"MinimapIcon"					"minimap_roshancamp"
		"MinimapIconSize"				"450"		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"witch_hex"   
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					""
		 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"15"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"155"
		"AttackDamageMax"			"185"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.5"
	    "AttackAcquisitionRange"    "600"
	    "AttackRange"           	"600"
	    "ProjectileModel"       	"particles/units/heroes/hero_death_prophet/death_prophet_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"70"
		"HealthBarOffset"			"260"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"2500"
		"BountyGoldMin"				"150"	
		"BountyGoldMax"				"200"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"210"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"15000"
		"StatusHealthRegen"			"15"	
		"StatusMana"				"1000"
		"StatusManaRegen"			"20.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"700"	
		"VisionNighttimeRange"		"700"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{

			"AttachWearables"
			{
		"Wearable1" {"ItemDef" "168"}//belt("Mourning Mother's Scarf")
		"Wearable2" {"ItemDef" "169"}//legs("Mourning Mother's Dress")
		"Wearable3" {"ItemDef" "170"}//armor("Mourning Mother's Top")
		"Wearable4" {"ItemDef" "171"}//head("Mourning Mother's Veil")
		"Wearable5" {"ItemDef" "172"}//ability_ultimate("Spirits of the Mourning Mother")
			}
			"EquippedItems"
			{
				"1"            	{"Item"        "item_aghanims_shard_roshan"}
			}
 
		}
	}	

"npc_witch_boss_2"	
	{
		// General
		//----------------------------------------------------------------
       		"vscripts"		"ai/ai_boss_ghost.lua"
		"Model"						"models/heroes/death_prophet/death_prophet.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_DeathProphet"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_death_prophet.vsndevts"
		"Level"						"8"
		"ModelScale" 				"1.2"	
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"
        "BoundsHullName"         "DOTA_HULL_SIZE_HERO"

 		"ConsideredHero"			"1"
		"MinimapIcon"					"minimap_roshancamp"
		"MinimapIconSize"				"450"		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"pugna_life_drain_witch"
		"Ability2"					"witch_hex"   
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					""
		 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"33"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"325"
		"AttackDamageMax"			"375"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.5"
	    "AttackAcquisitionRange"    "600"
	    "AttackRange"           	"600"
	    "ProjectileModel"       	"particles/units/heroes/hero_death_prophet/death_prophet_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"70"
		"HealthBarOffset"			"260"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"3500"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"210"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"25000"
		"StatusHealthRegen"			"30"	
		"StatusMana"				"1000"
		"StatusManaRegen"			"20.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"700"	
		"VisionNighttimeRange"		"700"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{

			"AttachWearables"
			{
		"Wearable1" {"ItemDef" "5597"}//belt("Mourning Mother's Scarf")
		"Wearable2" {"ItemDef" "5598"}//legs("Mourning Mother's Dress")
		"Wearable3" {"ItemDef" "5599"}//armor("Mourning Mother's Top")
		"Wearable4" {"ItemDef" "5600"}//head("Mourning Mother's Veil")
		"Wearable5" {"ItemDef" "5603"}//ability_ultimate("Spirits of the Mourning Mother")
			}
 
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_aghanims_shard_roshan"}
			}
		}
	}	

"npc_witch_boss_3"	
	{
		// General
		//----------------------------------------------------------------
       		"vscripts"		"ai/ai_boss_ghost.lua"
		"Model"						"models/heroes/death_prophet/death_prophet.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_DeathProphet"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_death_prophet.vsndevts"
		"Level"						"8"
		"ModelScale" 				"1.2"	
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"
        "BoundsHullName"         "DOTA_HULL_SIZE_HERO"

 		"ConsideredHero"			"1"
		"MinimapIcon"					"minimap_roshancamp"
		"MinimapIconSize"				"450"		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"pugna_life_drain_witch"
		"Ability2"					"witch_hex"   
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					""
		 

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"80"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"650"
		"AttackDamageMax"			"700"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.5"
	    "AttackAcquisitionRange"    "600"
	    "AttackRange"           	"600"
	    "ProjectileModel"       	"particles/units/heroes/hero_death_prophet/death_prophet_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"70"
		"HealthBarOffset"			"260"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"4500"
		"BountyGoldMin"				"240"	
		"BountyGoldMax"				"270"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"210"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"30000"
		"StatusHealthRegen"			"100"	
		"StatusMana"				"1000"
		"StatusManaRegen"			"20.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"700"	
		"VisionNighttimeRange"		"700"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{

			"AttachWearables"
			{
		"Wearable1" {"ItemDef" "14823"}//belt("Mourning Mother's Scarf")
		"Wearable2" {"ItemDef" "14824"}//legs("Mourning Mother's Dress")
		"Wearable3" {"ItemDef" "14826"}//armor("Mourning Mother's Top")
		"Wearable4" {"ItemDef" "14827"}//head("Mourning Mother's Veil")
		"Wearable5" {"ItemDef" "14828"}//ability_ultimate("Spirits of the Mourning Mother")
			}
 
  				"EquippedItems"
			{
				"1"            	{"Item"        "item_aghanims_shard_roshan"}
			}

		}
	}	
 		"npc_tombstone1"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/heroes/undying/undying_tower.vmdl" 
	"SoundSet"					"Undying_Tombstone"					// Name of sound set.
       "IsAncient"                  "1"
		"wearable"				"8630" 
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"zombie_tombstone"			// Ability 1.
		"Ability2"					"pudge_rot_tomb_1"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
 
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"14"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}

 		"npc_tombstone2"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/heroes/undying/undying_tower.vmdl" 
	"SoundSet"					"Undying_Tombstone"						// Name of sound set.
        "IsAncient"                  "1"
		"wearable"				"8630"		
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"zombie_tombstone"			// Ability 1.
		"Ability2"					"pudge_rot_tomb_2"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"			// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"18"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}
	

 		"npc_tombstone3"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/heroes/undying/undying_tower.vmdl" 
	"SoundSet"					"Undying_Tombstone"					// Name of sound set.
        "IsAncient"                  "1"
				"wearable"				"8630"
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"zombie_tombstone"			// Ability 1.
		"Ability2"					"pudge_rot_tomb_3"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"		// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"22"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
 
	}
	

 		"npc_tombstone4"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/heroes/undying/undying_tower.vmdl" 
	"SoundSet"					"Undying_Tombstone"					// Name of sound set.
        "IsAncient"                  "1"
				"wearable"				"8630"
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"zombie_tombstone"			// Ability 1.
		"Ability2"					"pudge_rot_tomb_4"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"		// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"26"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}
 
	
	 		"npc_tombstone_flash_3"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/items/undying/idol_of_ruination/idol_tower_gold_sim.vmdl" 
	"SoundSet"					"Undying_Tombstone"						// Name of sound set.
        "IsAncient"                  "1"
			"wearable"				"8630"	
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"zombie_tombstone"			// Ability 1.
		"Ability2"					"nevermore_dark_lord_2"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"			// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"30"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}
	
	 		"npc_tombstone_flash_4"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/items/undying/idol_of_ruination/idol_tower_sim.vmdl" 
	"SoundSet"					"Undying_Tombstone"						// Name of sound set.
        "IsAncient"                  "1"
			"wearable"				"8630"	
		"ModelScale"				"0.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"zombie_tombstone"			// Ability 1.
		"Ability2"					"abyssal_underlord_atrophy_aura_2"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"			// Hull type used for navigation/locomotion.
		"RingRadius"				"40"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"34"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}

	"npc_boss_ghoul"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/life_stealer/life_stealer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				"2.0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"ghoul_devourer"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"24"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"370"
		"AttackDamageMax"			"370"
		"AttackRate"				"0.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"60"
		"BountyGoldMin"				"20"	
		"BountyGoldMax"				"60"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"400"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}
	"npc_skelet_boss"	
	{
		// General
		//----------------------------------------------------------------
		
 		"vscripts"                  "ai/ai_skelet_boss.lua"
		
		"Model"						"models/items/wraith_king/arcana/wraith_king_arcana.vmdl"	// Model.
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_SkeletonKing"
		"GameSoundsFile"			"soundevents/game_sounds_skeletonking.vsndevts"
		"Level"						"25"
		"ModelScale" 				"1.7"
		"ConsideredHero"			"1"
		"IsAncient"					"1"
		"IsBossMonster"				"1"	
		"UseNeutralCreepBehavior" 	"0"
 
		"HasInventory"              "1"
		
		"MinimapIcon"				"minimap_roshancamp"
		"MinimapIconSize"			"950"

		// Abilities
		//----------------------------------------------------------------
   	"Ability1"					""		
 		"Ability2"					"skeleton_king_hellfire_blast_boss"
 		"Ability3"					"skeleton_king_vampiric_aura_boss"
 		"Ability4"					"skeleton_king_mortal_strike_boss"
	 	"Ability5"					"skeleton_king_reincarnation_boss"
 		"Ability6"					"skelet_mini"
 		"Ability7"					""				
 		"Ability8"					"ghoul_crazy_look"	
 	"Ability9"                  "boss_thirst"
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"105"			// Physical protection.
		"MagicalResistance"         "58"
		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"1910"					
		"AttackDamageMax"			"1940"	
		"AttackDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.5"				// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"800"	
		"AttackRange"				"120"
  
		"MovementSpeedActivityModifiers"
		{
			"walk"		"0"
			"run"		"345"
			"run_fast"	"373"
		}
		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"90"
		"HealthBarOffset"			"495"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"500"		// Experience earn.
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"		// Speed.	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1000000"		// Base health.
		"StatusHealthRegen"			"150.0"		// Health regeneration rate.
		"StatusMana"				"20000"			// Base mana.
		"StatusManaRegen"			"50.0"		// Mana regeneration rate.		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1000"		// Range of vision during day light.
		"VisionNighttimeRange"		"1000"		// Range of vision at night time.


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"						// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
		

 
			
			"DisableResistance"			"65.0"
 

			"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance_christmas_boss"}
				"2"            	{"Item"        "item_shivas_guard_christmas_boss"}
				"3"            	{"Item"        "item_assault_christmas_boss"}  
				"4"            	{"Item"        "item_sange_last"}

			}				
 
			 			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "13456" }
					"Wearable1" { "ItemDef" "13473" }
					"Wearable1" { "ItemDef" "13569" }
					"Wearable1" { "ItemDef" "13571" }
					"Wearable1" { "ItemDef" "13743" }
					"Wearable1" { "ItemDef" "13760" }
  				
				}		
 
		}
	}

	"npc_skelet_boss_mini"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/wraith_king/wk_ti8_creep/wk_ti8_creep_crimson.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_SkeletonKing"
		"GameSoundsFile"			"soundevents/game_sounds_skeletonking.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.2"
		"HasInventory"              "1"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					""
		"Ability3"					"skelet_fury_swipes"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"45"
		"MagicalResistance"         "55"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"125"
		"AttackDamageMax"			"135"
		"AttackRate"				"1.35"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"107"
		"BountyGoldMin"				"16"	
		"BountyGoldMax"				"20"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"750"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"7150"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 
 			"EquippedItems"
			{
				"1"            	{"Item"        "item_moon_shard"}
				"2"            	{"Item"        "item_moon_shard"}
				"3"            	{"Item"        "item_moon_shard"}  
 

			}
		}
	}  
//------Christmas---------
	"npc_christmas_boss"	
	{
		// General
		//----------------------------------------------------------------
		
 		"vscripts"                  "ai/ai_christmas_boss.lua"
		
		"Model"						"models/heroes/doom/doom.vmdl"	// Model.
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Roshan"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"25"
		"ModelScale" 				"1.7"
		"ConsideredHero"			"1"
		"IsAncient"					"1"
		"IsBossMonster"				"1"	
		"UseNeutralCreepBehavior" 	"0"
 
		"HasInventory"              "1"
		
		"MinimapIcon"				"minimap_roshancamp"
		"MinimapIconSize"			"950"

		// Abilities
		//----------------------------------------------------------------
   	"Ability1"					"doom_bringer_infernal_blade"		
 		"Ability2"					"doom_doom_lua"
 		"Ability3"					"boss_blink_strike"
 		"Ability4"					"ghoul_crazy_look"
	 	"Ability5"					"doom_devour_lua"
 		"Ability6"					""
 		"Ability7"					"doom_mini"				
 		"Ability8"					"blood"	
 	"Ability9"                  "boss_thirst"
 	"Ability10"                  "phantom_assassin_phantom_strike_lua"
 	"Ability11"                  ""
  	"Ability12"    	                                 "christmas_boss_music"
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"158"			// Physical protection.
		"MagicalResistance"         "95"
		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"2850"					
		"AttackDamageMax"			"3250"	
		"AttackDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AttackRate"				"1.3"
		"AttackAnimationPoint"		"0.5"				// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"800"	
		"AttackRange"				"120"
  

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"90"
		"HealthBarOffset"			"495"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"500"		// Experience earn.
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"		// Speed.	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"125000"		// Base health.
		"StatusHealthRegen"			"150.0"		// Health regeneration rate.
		"StatusMana"				"20000"			// Base mana.
		"StatusManaRegen"			"50.0"		// Mana regeneration rate.		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1000"		// Range of vision during day light.
		"VisionNighttimeRange"		"1000"		// Range of vision at night time.


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"						// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
		

 
			
			"DisableResistance"			"95.0"
 			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "6102" }
					"Wearable1" { "ItemDef" "17985" }
					"Wearable1" { "ItemDef" "17987" }
					"Wearable1" { "ItemDef" "17988" }
					"Wearable1" { "ItemDef" "17986" }
					"Wearable1" { "ItemDef" "6506" }
					"Wearable1" { "ItemDef" "9741" }
 				
				}

			"EquippedItems"
			{
				"1"            	{"Item"        "item_radiance_christmas_boss"}
				"2"            	{"Item"        "item_shivas_guard_christmas_boss"}
				"3"            	{"Item"        "item_assault_christmas_boss"}  
				"4"            	{"Item"        "item_sange_last"}

			}				
 
		
 
		}
	}
	"npc_warlock_boss"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"                  "ai/ai_warlock_boss.lua"

 

		"Model"						"models/heroes/warlock/warlock.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Warlock"
		"GameSoundsFile"			"soundevents/game_sounds_warlock.vsndevts"
		"Level"						"30"
		"ModelScale" 				"1.6"
		"ConsideredHero"			"1"
		"IsAncient"					"1"
		"IsBossMonster"				"1"	
		"UseNeutralCreepBehavior" 	"0"
 
		"HasInventory"              "1"
		
		"MinimapIcon"				"minimap_roshancamp"
		"MinimapIconSize"			"950"

		// Abilities
		//----------------------------------------------------------------
     	"Ability1"					"warlock_splesh"		
 		"Ability2"					""
 		"Ability3"					""
 		"Ability4"					"ghoul_crazy_look"
	 	"Ability5"					"warlock_terror"
 		"Ability6"					""
 
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"2000"			// Physical protection.
		"MagicalResistance"         "12"
		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"7500"
		"AttackDamageMax"			"9000"
		"AttackRate"				"1.9"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"900"
		"AttackRange"				"600"
		"ProjectileModel"			"particles/units/heroes/hero_warlock/warlock_base_attack.vpcf"
        "BaseAttackSpeed"			"140"		     
  

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"70"
		"HealthBarOffset"			"290"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"5000"		// Experience earn.
		"BountyGoldMin"				"0"		// Gold earned min.
		"BountyGoldMax"				"0"		// Gold earned max.

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"		// Speed.	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"600000"		// Base health.
		"StatusHealthRegen"			"0"		// Health regeneration rate.
		"StatusMana"				"15000"			// Base mana.
		"StatusManaRegen"			"30.0"		// Mana regeneration rate.		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1000"		// Range of vision during day light.
		"VisionNighttimeRange"		"1000"		// Range of vision at night time.


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"						// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		"Creature"
		{
 
			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "6473" }
					"Wearable1" { "ItemDef" "8947" }
					"Wearable1" { "ItemDef" "9862" }
					"Wearable1" { "ItemDef" "9861" }
					"Wearable1" { "ItemDef" "8941" }
					"Wearable1" { "ItemDef" "14302" }
 				
				}
 
		}
	}
	"npc_classic_toxic_veno_boss"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/venomancer/venomancer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_ranged"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"25"
		"ModelScale" 				"1.4"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"zombie_poison_sting_big"
		"Ability2"					"respawn"
		"Ability3"					"death_prophet_spirit_siphon"	
		"Ability4"					"enchantress_untouchable"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"99"
		"MagicalResistance"         "48"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"180"
		"AttackDamageMax"			"200"
		"AttackRate"				"2.0"
		"AttackAnimationPoint"		"1.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"400"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"100"
		"BountyGoldMin"				"400"	
		"BountyGoldMax"				"550"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"375"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4000"
		"StatusHealthRegen"			"50"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 		
				"OffensiveAbilities"
			{
				"Ability3"
				{
					"Name"					"death_prophet_spirit_siphon"										
				}
			}
				"AttachWearables"
			{
				"Wearable1"	{ "ItemDef"	"9334" }
				"Wearable2"	{ "ItemDef"	"9335" }
				"Wearable3"	{ "ItemDef"	"9336" }
				"Wearable4"	{ "ItemDef"	"9338" }	
			}
			
		}	
	}
	"npc_classic_phoenix_boss"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/phoenix/phoenix_bird.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_ranged"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"25"
		"ModelScale" 				"2.2"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"phoenix_supernova"
		"Ability2"					"phoenix_fire"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					""
		"Ability6"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"70"
		"MagicalResistance"         "56"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"400"
		"AttackDamageMax"			"500"
		"AttackRate"				"0.9"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"400"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"10000"
		"BountyGoldMin"				"1900"	
		"BountyGoldMax"				"2100"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"3500"
		"StatusHealthRegen"			"10"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
				"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"phoenix_supernova"										
				}

				
			}

			"AttachWearables"
				{
					"Wearable1"	{ "ItemDef"	"14993" }	
					"Wearable2"	{ "ItemDef"	"7458" }	
					"Wearable3"	{ "ItemDef"	"13714" }	
				}
		}
				
	}
	"npc_classic_alduin_boss"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/dragon_knight/dragon_knight_dragon.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_ranged"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"25"
		"ModelScale" 				"2.2"
		"UseNeutralCreepBehavior"	"1"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_desolate"
		"Ability2"					"ability_reincarnation"
		"Ability3"					"anduin_sekelet"	
		"Ability4"					"anudin_reduce_damage"
		"Ability5"					"ability_dispersion"
		"Ability6"					"huskar_burning_spear"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"400"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1200"
		"AttackDamageMax"			"3500"
		"AttackRate"				"0.9"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"400"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"100"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"10000"
		"BountyGoldMin"				"1900"	
		"BountyGoldMax"				"2100"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"525"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"400000"
		"StatusHealthRegen"			"2000"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 		
			"EquippedItems"
			{
				"1"            	{"Item"        "item_bloodstone_max_2"}
			}
 
					
			"OffensiveAbilities"
			{
				"Ability3"
				{
					"Name"					"anduin_sekelet"										
				}
				
			}	
		}	
	}


}