// Units File

"DOTAUnits"
{
 
	"npc_classic_wave_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"
        "BoundsHullName"         "DOTA_HULL_SIZE_REGULAR"
		"UseNeutralCreepBehavior"	"0"
		
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					""
	//	"Ability3"					"zombie_passive"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"6"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"38"
		"AttackDamageMax"			"44"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"1100"
		"AttackRange"				"125"
        "BaseAttackSpeed"			"140"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"23"
		"BountyGoldMin"				"3"	
		"BountyGoldMax"				"5"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"280"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"615"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
 
	}
	

 "npc_suic_wave_zombie"	
	{
 		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/heroes/undying/undying_minion.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"3"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"0"
 

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"zombie_suic"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""
	//	"Ability5"		            "zombie_passive"
		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"6"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"38"
		"AttackDamageMax"			"44"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"1100"
		"AttackRange"				"90"
        "BaseAttackSpeed"			"140"	  

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"23"
		"BountyGoldMin"				"18"	
		"BountyGoldMax"				"25"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"615"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

 
	}
	

"npc_undying_1"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undying.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.3"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_1"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""
//		"Ability5"		"zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"8"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"105"
		"AttackDamageMax"			"115"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"1100"
		"AttackRange"				"180"
        "BaseAttackSpeed"			"140"	 	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"80"
		"HealthBarOffset"			"245"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"160"
		"BountyGoldMin"				"100"	
		"BountyGoldMax"				"120"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1450"
		"StatusHealthRegen"			"0"
		"StatusMana"				"550"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "392" }
					"Wearable1" { "ItemDef" "393" }
					"Wearable1" { "ItemDef" "542" }
					"Wearable1" { "ItemDef" "616" }
 
 
 				
				}
 	
			
		}
	}
	

	"npc_seerdying_1"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undyindg.lua"
		"Model"						"models/heroes/undying/undying.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.0"
		"UseNeutralCreepBehavior"	"0"
 

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"necronomicon_warrior_sight"
//		"Ability2"					"zombie_passive"
		"Ability3"					""	
		"Ability4"					""
		

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"8"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"105"
		"AttackDamageMax"			"115"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"1100"
		"AttackRange"				"180"
        "BaseAttackSpeed"			"140"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"150"
		"BountyGoldMin"				"100"	
		"BountyGoldMax"				"120"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1450"
		"StatusHealthRegen"			"0"
		"StatusMana"				"550"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
	 

					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "14963" }
 
 				
				}		
			
		}
	}
}
