// Units File

"DOTAUnits"
{
	"Version"	"1"
	
// Wave undyings

	"npc_cemetery_skelet"	
	{
		// General
		//----------------------------------------------------------------
        "vscripts"        "ai/ai_cemetery_skelet.lua"
		"Model"						"models/creeps/neutral_creeps/n_creep_troll_skeleton/n_creep_skeleton_melee.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.15"
		"UseNeutralCreepBehavior" 	"0"
		"HasInventory"				"1"
		"IsAncient"					"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"zombie_passive"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""
		"Ability5"					""    
		"Ability6"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"4"
		"MagicalResistance"         "30"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"182"
		"AttackDamageMax"			"190"
		"AttackRate"				"1.2"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"185"
		"BountyGoldMin"				"65"	
		"BountyGoldMax"				"70"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2200"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_hyperstone"}

			}	
		}
	}

	"npc_classic_pig"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/props_gameplay/pig.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"primal_beast_onslaught"
		"Ability3"					""	
		"Ability4"					"respawn"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"12"
		"MagicalResistance"         "10"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"9"
		"AttackDamageMax"			"12"
		"AttackRate"				"0.5"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"4"
		"BountyGoldMin"				"6"	
		"BountyGoldMax"				"9"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"220"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"155"
		"StatusHealthRegen"			"5.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "12.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
			"OffensiveAbilities"
			{
				"Ability2"
				{
					"Name"					"primal_beast_onslaught"										
				}
				
			}
		}
	}

	"npc_classic_sheep"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/hex/sheep_hex/sheep_hex.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ability_mist_coil"
		"Ability2"					"respawn"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"4"
		"MagicalResistance"         "55"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"16"
		"AttackDamageMax"			"24"
		"AttackRate"				"1"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"150"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"4"
		"BountyGoldMin"				"5"	
		"BountyGoldMax"				"9"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"325"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"120"
		"StatusHealthRegen"			"1.2"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "15.0"
			        "Support"       "30.0"
			        "RoamDistance"  "400.0"
			    }
			}
			"OffensiveAbilities"
			{
				"Ability2"
				{
					"Name"					"ability_mist_coil"										
				}
				
			}
		}
	}
"npc_classic_frog"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"                  "ai/mobs/ai_frog.lua"
		"Model"						"models/props_gameplay/frog.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"3"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"slow_mobs"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					"respawn"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"6"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"41"
		"AttackDamageMax"			"52"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"150"
        "BaseAttackSpeed"			"100"	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"36"
		"BountyGoldMin"				"18"	
		"BountyGoldMax"				"26"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"295"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"345"
		"StatusHealthRegen"			"1.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"
		"VisionNighttimeRange"		"800"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"


		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "70.0"
			        "Avoidance"     "5.0"
			        "Support"       "25.0"
			        "RoamDistance"  "400.0"
			    }
			}
			
		}
 
	}
	"npc_classic_chicken"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/hex/fish_hex/fish_hex.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"12"
		"ModelScale" 				"1"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn"
		"Ability3"					"fish_pounce"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"14"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"225"
		"AttackDamageMax"			"245"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"50"
		"BountyGoldMin"				"45"	
		"BountyGoldMax"				"55"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"255"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"620"
		"StatusHealthRegen"			"10"
		"StatusMana"				"500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 
			
			"OffensiveAbilities"
			{
				"Ability3"
				{
					"Name"					"fish_pounce"										
				}
				
			}
			
 
		}
	}
	"npc_classic_not_fish"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/props_gameplay/chicken.vmdl"
		"BaseClass"					"npc_dota_creature"
		"vscripts"                  "ai/mobs/ai_not_fish.lua"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"9"
		"ModelScale" 				"1"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn"
		"Ability3"					"frozen_zombie_attack"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"4"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"125"
		"AttackDamageMax"			"175"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"26"
		"BountyGoldMin"				"25"	
		"BountyGoldMax"				"30"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"255"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"550"
		"StatusHealthRegen"			"10"
		"StatusMana"				"500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"EquippedItems"
			{
				"1"            	{"Item"        "item_moon_shard"}
			}
			
 
		}
	}
	"npc_classic_not_fish_2"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/props_gameplay/chicken.vmdl"
		"BaseClass"					"npc_dota_creature"
		"vscripts"                  "ai/mobs/ai_not_fish.lua"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"9"
		"ModelScale" 				"1"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn"
		"Ability3"					"frozen_zombie_attack"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"18"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"95"
		"AttackDamageMax"			"155"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"26"
		"BountyGoldMin"				"25"	
		"BountyGoldMax"				"30"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"255"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"690"
		"StatusHealthRegen"			"10"
		"StatusMana"				"500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"EquippedItems"
			{
				"1"            	{"Item"        "item_moon_shard"}
			}
			
 
		}
	}
	"npc_classic_woobleydog"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/neutral_creeps/n_creep_worg_large/n_creep_worg_large.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"20"
		"ModelScale" 				"1"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					"respawn"
		"Ability3"					"woobleydog_blade_dance"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"55"
		"MagicalResistance"         "36"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"420"
		"AttackDamageMax"			"465"
		"AttackRate"				"1.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"110"
		"BountyGoldMin"				"150"	
		"BountyGoldMax"				"170"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"375"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"3000"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 
			"EquippedItems"
			{
				"1"            	{"Item"        "item_moon_shard"}
			}
			
		}
	}
	"npc_classic_woobleydog2"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/neutral_creeps/n_creep_worg_small/n_creep_worg_small.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"15"
		"ModelScale" 				"1"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"woobleydog_earthshake"
		"Ability2"					"respawn"
		"Ability3"					"woobleydog_blade_dance"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"44"
		"MagicalResistance"         "12"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"480"
		"AttackDamageMax"			"520"
		"AttackRate"				"1.5"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"90"
		"BountyGoldMin"				"50"	
		"BountyGoldMax"				"90"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"375"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2450"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 				"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"woobleydog_earthshake"										
				}
				
			}
			
			
		}
	}
	"npc_classic_microchel"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/neutral_creeps/n_creep_troll_skeleton/n_creep_skeleton_melee.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"15"
		"ModelScale" 				"1"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"microchel_rage"
		"Ability2"					"respawn"
		"Ability3"					"microchel_natural_order"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"111"
		"MagicalResistance"         "24"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"650"
		"AttackDamageMax"			"720"
		"AttackRate"				"1.9"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"160"
		"BountyGoldMin"				"160"	
		"BountyGoldMax"				"190"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"375"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4500"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 				"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"microchel_rage"										
				}
				
			}
			
			
		}
	}
	"npc_classic_skelet_ruin"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/ice_biome/undeadtusk/undead_tuskskeleton_armor01.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_ranged"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"25"
		"ModelScale" 				"1"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"skelet_ruin_latent_poison"
		"Ability2"					"respawn"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"91"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"770"
		"AttackDamageMax"			"890"
		"AttackRate"				"1.4"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"900"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"220"
		"BountyGoldMin"				"180"	
		"BountyGoldMax"				"210"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"375"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4500"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 				"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"skelet_ruin_latent_poison"										
				}
				
			}
			"EquippedItems"
			{
				"1"            	{"Item"        "item_freez_shivas_guard"}
			}
			
			
		}
	}
	"npc_classic_half_zombie"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/undying/undying_minion_torso.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"Level"						"8"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"41"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"5200"
		"AttackDamageMax"			"7400"
		"AttackRate"				"2.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"300"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"90"
		"BountyGoldMin"				"160"	
		"BountyGoldMax"				"220"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"550"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"25000"
		"StatusHealthRegen"			"0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"500"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
	}
	"npc_classic_witch"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/neutral_creeps/n_creep_ghost_a/n_creep_ghost_a.vmdl"
		"BaseClass"					"npc_dota_creature"
		"vscripts"                  "ai/mobs/ai_witch.lua"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"1"
		"ModelScale" 				"0.6"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_magick_attack"
		"Ability2"					"ghost_elusive_1"
		"Ability3"					"respawn"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"
		"MagicalResistance"         "10"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"15"
		"AttackDamageMax"			"20"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "5000"
	    "AttackRange"           	"350"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"12"
		"BountyGoldMin"				"18"	
		"BountyGoldMax"				"24"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"225"
		"StatusHealthRegen"			"0.5"	
		"StatusMana"				"0"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"	
		"VisionNighttimeRange"		"5000"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "20.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
		}
	}	

 
//------Halloween---------


 		"npc_tombstone_clock"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"
 
		"Model"						"models/items/rattletrap/the_neuromaniac_experiment_subject_no08/the_neuromaniac_experiment_subject_no08.vmdl" 
	"SoundSet"					"Undying_Tombstone"					// Name of sound set.
        "IsAncient"                  "1"
				"wearable"				"8630"
		"ModelScale"				"2.8"

		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"golden_mine_passive_5"			// Ability 1.
		"Ability2"					"pudge_rot_tomb_clock"			// Ability 2.
		"Ability3"					"neutral_spell_immunity"			// Ability 3.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"			"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin"			"0"			// Damage range min.
		"AttackDamageMax"			"0"			// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"0"			// Speed of attack.
		"AttackAnimationPoint"		"0"			// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"0"			// Range within a target can be acquired.
		"AttackRange"				"0"			// Range within a target can be attacked.
		"ProjectileModel"			""			// Particle system model for projectile.
		"ProjectileSpeed"			"0"			// Speed of projectile.


		// Bounty
		//----------------------------------------------------------------
		"BountyGoldMin"				"1"		// Gold earned min.
		"BountyGoldMax"				"1"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"		// Hull type used for navigation/locomotion.
		"RingRadius"				"80"
		"HealthBarOffset"			"260"
		"MinimapIconSize"			"200"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0"			// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"10"		// Base health.
		"StatusHealthRegen"			"0"			// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_BUILDING"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"		// Range of vision during day light.
		"VisionNighttimeRange"		"600"		// Range of vision at night time.
		
 
	}	
 

	"npc_undying_clock"	
	{
		// General
		//----------------------------------------------------------------
		
		"vscripts"		"ai/ai_undying.lua"
		"Model"						"models/heroes/rattletrap/rattletrap.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Undying"
		"GameSoundsFile"			"soundevents/game_sounds_undying.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.45"
		"UseNeutralCreepBehavior"	"0"
		"HasInventory"				"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"tombestone_und_clock"
		"Ability2"					"ghoul_crazy_look"
		"Ability3"					""	
		"Ability4"					""
		"Ability5"		"zombie_passive"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"85"
		"MagicalResistance"         "60"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1450"
		"AttackDamageMax"			"1475"
		"AttackRate"				"2.3"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"180"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"860"
		"BountyGoldMin"				"620"	
		"BountyGoldMax"				"850"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"225"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"12500"
		"StatusHealthRegen"			"45"
		"StatusMana"				"350"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"
		"VisionNighttimeRange"		"900"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		"Creature"
		{
		
					"AttachWearables"
				{
					"Wearable1" { "ItemDef" "17951" }  
					"Wearable1" { "ItemDef" "17952" }
 					"Wearable1" { "ItemDef" "17953" }
 				
				}
					"DisableResistance"			"35.0"
 
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_hyperstone"}
			}	 	
			
		}
	}
//------Christmas---------
	"npc_classic_mini_crampus"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/doom/doom.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"1"
		"ModelScale" 				"0.3"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"doom_bringer_infernal_blade_mini"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"60"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1150"
		"AttackDamageMax"			"1250"
		"AttackRate"				"0.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"107"
		"BountyGoldMin"				"16"	
		"BountyGoldMax"				"20"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"750"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"6550"
		"StatusHealthRegen"			"0.5"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 
			 			"AttachWearables"
				{
					"Wearable1" { "ItemDef" "8502" }
					"Wearable1" { "ItemDef" "8507" }
					"Wearable1" { "ItemDef" "8504" }
					"Wearable1" { "ItemDef" "8508" }
					"Wearable1" { "ItemDef" "8505" }
					"Wearable1" { "ItemDef" "8506" }
					"Wearable1" { "ItemDef" "8503" }
 				
				}
									"OffensiveAbilities"
			{
				"Ability2"
				{
					"Name"					"doom_bringer_infernal_blade_mini"										
				}
				
			}
		}
	}

	"npc_classic_doom_crampus"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/items/warlock/golem/ahmhedoq/ahmhedoq.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_LifeStealer"
		"GameSoundsFile"			"soundevents/game_sounds_life_stealer.vsndevts"
		"Level"						"1"
		"ModelScale" 				"1.2"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					"doom_aura"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"65"
		"MagicalResistance"         "80"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"2340"
		"AttackDamageMax"			"2628"
		"AttackRate"				"0.75"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"107"
		"BountyGoldMin"				"16"	
		"BountyGoldMax"				"20"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"750"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"18680"
		"StatusHealthRegen"			"150.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 
 
 
		}
	}

"npc_greevil"
{
// General
//--------------------------------------------------------------—
 		"vscripts"                  "ai/ai_greevil.lua"
 		
"BaseClass" "npc_dota_creature"
"Model" "models/courier/greevil/gold_greevil.vmdl"
"ModelScale" "3.5"
"Level" "10"
"HealthBarOffset" "140"
"HasInventory" "0"
 
		"IsAncient"					"1"
		"IsBossMonster"				"1"	
"UseNeutralCreepBehavior" "0"


// Abilities
//--------------------------------------------------------------—
"Ability1" "greevil"
"Ability2" ""
"Ability3" ""
"Ability4" ""


// Armor
//--------------------------------------------------------------—
"ArmorPhysical" "0"
"MagicalResistance" "0"

// Attack
//--------------------------------------------------------------—
"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
"AttackDamageMin" "0"
"AttackDamageMax" "0"

// Bounty
//--------------------------------------------------------------—
"BountyGoldMin" "0.0"
"BountyGoldMax" "0.0"

// Bounds
//--------------------------------------------------------------—
"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
"RingRadius" "30"
"CollisionSize" "1"


// Movement
//--------------------------------------------------------------—
"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
"MovementSpeed" "550"

// Status
//--------------------------------------------------------------—
"StatusHealth" "1000000000"
"StatusHealthRegen" "10000"
"StatusMana" "0"
"StatusManaRegen" "0"

// Vision
//--------------------------------------------------------------—
"VisionDaytimeRange" "900"
"VisionNighttimeRange" "900"

// Team
//--------------------------------------------------------------—
"TeamName" "DOTA_TEAM_BADGUYS"
"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
"UnitRelationshipClass" "DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

	}

		"npc_classic_new_years"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/ice_biome/frostbitten/n_creep_frostbitten_swollen01.vmdl"
		"BaseClass"					"npc_dota_creature"
		"Level"						"4"
		"ModelScale" 				"0.8"
 
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"frozen_zombie_attack"
		"Ability2"					"ghoul_crazy_look"  
		"Ability3"					"zombie_passive"	
		"Ability4"					""
		"Ability5"		            ""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"25"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"920"
		"AttackDamageMax"			"950"
		"AttackRate"				"1.8"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"90"
        "BaseAttackSpeed"			"160"		     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"180"
		"BountyGoldMin"				"36"	
		"BountyGoldMax"				"42"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"450"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"3500"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"0"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"5000"
		"VisionNighttimeRange"		"5000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}
 
		}
	}

		"npc_classic_new_years_lich"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/lich/lich.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_magick_attack_4"
		"Ability2"					"ghost_elusive_3"
		"Ability3"					"zombie_passive"	
		"Ability4"					"lich_chain_frost"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"30"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.3"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "5000"
	    "AttackRange"           	"350"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"155"
		"BountyGoldMin"				"150"	
		"BountyGoldMax"				"155"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"300"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4350"
		"StatusHealthRegen"			"0.0"	
		"StatusMana"				"2000"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"	
		"VisionNighttimeRange"		"900"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}

														"OffensiveAbilities"
			{
				"Ability5"
				{
					"Name"					"lich_chain_frost"											
				}				
			}

						"AttachWearables"
				{
					"Wearable1" { "ItemDef" "9756" }
					"Wearable1" { "ItemDef" "14998" }
					"Wearable1" { "ItemDef" "7576" }
				}
		}
	}

			"npc_classic_new_years_winterwyvern"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/winterwyvern/winterwyvern.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"range_magick_attack_5"
		"Ability2"					"ghost_elusive_3"
		"Ability3"					"zombie_passive"	
		"Ability4"					"winter_wyvern_winters_curse"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"35"
		"MagicalResistance"         "0"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"0"
		"AttackDamageMax"			"0"
		"AttackRate"				"1.5"
		"AttackAnimationPoint"		"0.4"
	    "AttackAcquisitionRange"    "5000"
	    "AttackRange"           	"350"
	    "ProjectileModel"       	"particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
	    "ProjectileSpeed"       	"1000"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"155"
		"BountyGoldMin"				"200"	
		"BountyGoldMax"				"215"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_FLY"
		"MovementSpeed"				"300"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"4250"
		"StatusHealthRegen"			"0.0"	
		"StatusMana"				"3500"
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"900"	
		"VisionNighttimeRange"		"900"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"	


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"	
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"DefaultState"       "Invade"
			"States"
			{
			    "Invade"
			    {
			        "Name"          "Invade"
			        "Aggression"    "100.0"
			        "Avoidance"     "0.0"
			        "Support"       "0.0"
			        "RoamDistance"  "400.0"
			    }
			}

														"OffensiveAbilities"
			{
				"Ability4"
				{
					"Name"					"winter_wyvern_winters_curse"											
				}				
			}

						"AttachWearables"
				{
					"Wearable1" { "ItemDef" "8017" }
					"Wearable1" { "ItemDef" "7292" }
				}
		}
	}	


		"npc_classic_new_years_ancient"	
	{
		// General
		//----------------------------------------------------------------
				"vscripts"		"ai/ai_ancient.lua"

		"Model"						"models/heroes/ancient_apparition/ancient_apparition.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"Hero_Bane.Attack"
		"GameSoundsFile"			"soundevents/game_sounds_heroes/game_sounds_bane.vsndevts"
		"Level"						"1"
		"ModelScale" 				".9"
		"UseNeutralCreepBehavior"	"0"
		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"ghoul_crazy_look"
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					"zombie_passive"
		"Ability5"		            "essence_freezing_field"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"35"
		"MagicalResistance"         "25"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"1250"
		"AttackDamageMax"			"1320"
		"AttackRate"				"1.7"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"5000"
		"AttackRange"				"225"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"180"
		"BountyGoldMin"				"0"	
		"BountyGoldMax"				"0"	

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"500"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"6150"
		"StatusHealthRegen"			"0.0"
		"StatusMana"				"1300"	
		"StatusManaRegen"			"25.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1000"
		"VisionNighttimeRange"		"1000"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_BADGUYS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 
			
 

									"AttachWearables"
				{
					"Wearable1" { "ItemDef" "7462" }
					"Wearable1" { "ItemDef" "9462" }
				}
		}
	}	

	"npc_classic_microchel"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/neutral_creeps/n_creep_troll_skeleton/n_creep_skeleton_melee.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"15"
		"ModelScale" 				"1"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"microchel_rage"
		"Ability2"					"respawn"
		"Ability3"					"microchel_natural_order"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"11"
		"MagicalResistance"         "24"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"9900"
		"AttackDamageMax"			"12000"
		"AttackRate"				"1.4"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"160"
		"BountyGoldMin"				"160"	
		"BountyGoldMax"				"190"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"375"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"9550"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 				"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"microchel_rage"										
				}
				
			}
			
			
		}
	}
	"npc_classic_skelet_ruin"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/ice_biome/undeadtusk/undead_tuskskeleton_armor01.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_ranged"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"25"
		"ModelScale" 				"1"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"skelet_ruin_latent_poison"
		"Ability2"					"respawn"
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"9"
		"MagicalResistance"         "75"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"3750"
		"AttackDamageMax"			"4800"
		"AttackRate"				"1.4"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"900"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"220"
		"BountyGoldMin"				"180"	
		"BountyGoldMax"				"210"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"375"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"11900"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 				"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"skelet_ruin_latent_poison"										
				}
				
			}
			"EquippedItems"
			{
				"1"            	{"Item"        "item_freez_shivas_guard"}
			}
			
			
		}
	}
	"npc_creep_impossible"	
	{
		// General
		//----------------------------------------------------------------
		"vscripts"		"ai/wave/ai_zombie.lua"
		"Model"						"models/items/undying/idol_of_ruination/ruin_wight_minion_gold.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"25"
		"ModelScale" 				"2.6"
		"UseNeutralCreepBehavior"	"0"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					""
		"Ability2"					""
		"Ability3"					""	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"100"
		"MagicalResistance"         "100"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"5400"
		"AttackDamageMax"			"6200"
		"AttackRate"				"0.9"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"400"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"100"
		"BountyGoldMin"				"200"	
		"BountyGoldMax"				"250"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"375"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"75000"
		"StatusHealthRegen"			"100"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

	}
	"npc_classic_toxic_veno"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/heroes/venomancer/venomancer.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Melee"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"30"
		"ModelScale" 				"1.2"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"zombie_poison_sting_big"
		"Ability2"					"respawn"
		"Ability3"					"ghoul_crazy_look"	
		"Ability4"					""

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"77"
		"MagicalResistance"         "12"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"220"
		"AttackDamageMax"			"240"
		"AttackRate"				"2"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"150"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"90"
		"BountyGoldMin"				"425"	
		"BountyGoldMax"				"625"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"475"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1700"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 			
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_desolator_2_custom"}
				"1"            	{"Item"        "item_vampire_claw"}
				"1"            	{"Item"        "item_moon_shard"}
			}
			
				"AttachWearables"
			{
				"Wearable1"	{ "ItemDef"	"13084" }	
				"Wearable2"	{ "ItemDef"	"13106" }	
				"Wearable3"	{ "ItemDef"	"13107" }	
				"Wearable4"	{ "ItemDef"	"13108" }	
			}
		}
	}
	"npc_classic_dragon_small"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/neutral_creeps/n_creep_dragonspawn_b/n_creep_dragonspawn_b.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Ranged"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"30"
		"HasInventory"				"1"
		"ModelScale" 				"0.9"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"huskar_burning_spear"
		"Ability2"					"respawn"
		"Ability3"					"ghoul_crazy_look"	
		"Ability4"					"huskar_berserkers_blood"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"70"
		"MagicalResistance"         "12"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"160"
		"AttackDamageMax"			"170"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"350"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"90"
		"BountyGoldMin"				"150"	
		"BountyGoldMax"				"170"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"375"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1800"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 			
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_desolator_2_custom"}
				"1"            	{"Item"        "item_vampire_claw"}
			}
			"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"huskar_burning_spear"										
				}
			}
		}
	}
	"npc_classic_dragon_big"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/neutral_creeps/n_creep_dragonspawn_a/n_creep_dragonspawn_a.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Ranged"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"30"
		"HasInventory"				"1"
		"ModelScale" 				"1.2"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"huskar_burning_spear"
		"Ability2"					"respawn"
		"Ability3"					"ghoul_crazy_look"	
		"Ability4"					"huskar_berserkers_blood"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"90"
		"MagicalResistance"         "12"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"210"
		"AttackDamageMax"			"230"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"350"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"90"
		"BountyGoldMin"				"150"	
		"BountyGoldMax"				"170"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"375"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2255"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 			
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_moon_shard"}
			}
			"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"huskar_burning_spear"										
				}
			}
		}
	}
	"npc_classic_dragon"	
	{
		// General
		//----------------------------------------------------------------
		"Model"						"models/creeps/neutral_creeps/n_creep_black_dragon/n_creep_black_dragon.vmdl"
		"BaseClass"					"npc_dota_creature"
		"SoundSet"					"n_creep_Ranged"
		"GameSoundsFile"			"soundevents/game_sounds_creeps.vsndevts"
		"ConsideredHero"			"1"
		"Level"						"20"
		"ModelScale" 				"1.2"
		"HasInventory"				"1"
		"UseNeutralCreepBehavior"	"1"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"huskar_burning_spear"
		"Ability2"					"respawn"
		"Ability3"					"ghoul_crazy_look"	
		"Ability4"					"huskar_berserkers_blood"

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"55"
		"MagicalResistance"         "12"

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackDamageMin"			"190"
		"AttackDamageMax"			"220"
		"AttackRate"				"1.6"
		"AttackAnimationPoint"		"0.4"
		"AttackAcquisitionRange"	"500"
		"AttackRange"				"350"
	     

		// Bounds
		//----------------------------------------------------------------
		"RingRadius"				"40"
		"HealthBarOffset"			"170"

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"90"
		"BountyGoldMin"				"150"	
		"BountyGoldMax"				"170"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"375"	
		

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1255"
		"StatusHealthRegen"			"20"
		"StatusMana"				"1500"	
		"StatusManaRegen"			"0.0"		 
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"500"
		"VisionNighttimeRange"		"300"


		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_NEUTRALS"
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"

		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
 			
 						"EquippedItems"
			{
				"1"            	{"Item"        "item_moon_shard"}
			}
			"OffensiveAbilities"
			{
				"Ability1"
				{
					"Name"					"huskar_burning_spear"										
				}
			}
		}
	}
	"npc_dota_venomancer_plague_ward"
	{
		// General
		//----------------------------------------------------------------
		"BaseClass"					"npc_dota_venomancer_plagueward"	// Class of entity of link to.
		"Model"						"models/items/venomancer/ward/chomper_ward/chomper_ward.vmdl"	// Model.
		"SoundSet"					"Hero_VenomancerWard"					// Name of sound set.
		"Level"						"1"
		"ModelScale" 				"1.2"
		"SelectionGroup"			"Venomancer_Wards"
		"UnitLabel"			"plaguewards"
		"wearable"				"684"

		// Abilities
		//----------------------------------------------------------------
		"Ability1"					"creep_piercing"			// Ability 1.
		"Ability2"					"venomancer_area_poison"			// Ability 2.
		"Ability3"					"ghoul_crazy_look"			// Ability 3.
		"Ability4"					"zombie_poison_sting_big"			// Ability 4.
		"Ability5"					""			// Ability 5.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"0"			// Physical protection.
		"MagicalResistance"				"0"			// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"3420"			// Damage range min.
		"AttackDamageMax"			"4540"		// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"1.4"		// Speed of attack.
		"AttackAnimationPoint"		"0.3"		// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"600"		// Range within a target can be acquired.
		"AttackRange"				"600"		// Range within a target can be attacked.
		"ProjectileModel"			"particles/units/heroes/hero_venomancer/venomancer_plague_ward_projectile.vpcf" // Particle system model for projectile.
		"ProjectileSpeed"			"1900"		// Speed of projectile.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_HERO"			// Hull type used for navigation/locomotion.
		"HealthBarOffset"			"170"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_NONE"			// Type of locomotion - ground, air
		"MovementSpeed"				"0"			// Speed
		"MovementTurnRate"			"0.5"		// Turning rate.
	
		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"20"		// Experience earn.
		"BountyGoldMin"				"15"		// Gold earned min.
		"BountyGoldMax"				"15"		// Gold earned max.

			// Status
		//----------------------------------------------------------------
		"StatusHealth"				"2700"		// Base health.
		"StatusHealthRegen"			"0.25"		// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_GOODGUYS"			// Team name.
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_WARD"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"800"		// Range of vision during day light.
		"VisionNighttimeRange"		"800"		// Range of vision at night time.

		//Inventory
		"HasInventory"				"0"
	}
}