"DOTAUnits"
{
	"npc_spirit_sargatanas_hell_summon"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"	// Class of entity of link to.
		"Model"						"models/heroes/brewmaster/brewmaster_firespirit.vmdl"	// Model.
		"SoundSet"					"Creep_Good_Range"					// Name of sound set.
		"ModelScale"				"0.75"
		"Level"						"1"
		"IsSummoned"				"1"
		"SelectionGroup"			"Spirits"
		"UnitLabel"			"Spirits"
		
		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"ability_firecleave_creep"			// Ability 1.
		"Ability2"					""			// Ability 2.
		"Ability3"					""			// Ability 3.
		"Ability4"					""			// Ability 4.
		"Ability5"					""			// Ability 5.
		"Ability6"					""			// Ability 6 - Extra.
		"Ability7"					""			// Ability 7 - Extra.
		"Ability8"					""			// Ability 8 - Extra.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"2"			// Physical protection.
		"MagicalResistance"				"40"		// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"2"		// Damage range min.
		"AttackDamageMax"			"6"		// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"1.8"			// Speed of attack.
		"AttackAnimationPoint"		"0.2"		// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"800"		// Range within a target can be acquired.
		"AttackRange"				"500"		// Range within a target can be attacked.
		"ProjectileModel"			"particles/units/heroes/hero_lina/lina_base_attack.vpcf" // Particle system model for projectile.
		"ProjectileSpeed"			"900"		// Speed of projectile.

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"10"		// Experience earn.
		"BountyGoldMin"				"18"		// Gold earned min.
		"BountyGoldMax"				"24"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_SMALL"			// Hull type used for navigation/locomotion.
		"HealthBarOffset"			"130"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"			// Type of locomotion - ground, air
		"MovementSpeed"				"280"		// Speed
		"MovementTurnRate"			"0.9"		// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"170"		// Base health.
		"StatusHealthRegen"			"4"		// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_GOODGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_HERO"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1200"		// Range of vision during day light.
		"VisionNighttimeRange"		"800"		// Range of vision at night time.
	}
	"npc_golem_sargatanas_hell_summon"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"	// Class of entity of link to.
		"Model"						"models/items/warlock/golem/ti_8_warlock_darkness_apostate_golem/ti_8_warlock_darkness_apostate_golem.vmdl"	// Model.
		"SoundSet"					"Creep_Good_Range"					// Name of sound set.
		"ModelScale"				"0.55"
		"Level"						"1"
		"IsSummoned"				"1"
		"SelectionGroup"			"Spirits"
		"UnitLabel"			"Spirits"
		
		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"ability_firecleave_creep"			// Ability 1.
		"Ability2"					""			// Ability 2.
		"Ability3"					""			// Ability 3.
		"Ability4"					""			// Ability 4.
		"Ability5"					""			// Ability 5.
		"Ability6"					""			// Ability 6 - Extra.
		"Ability7"					""			// Ability 7 - Extra.
		"Ability8"					""			// Ability 8 - Extra.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"2"			// Physical protection.
		"MagicalResistance"				"40"		// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"54"		// Damage range min.
		"AttackDamageMax"			"57"		// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"1.5"			// Speed of attack.
		"AttackAnimationPoint"		"0.2"		// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"800"		// Range within a target can be acquired.
		"AttackRange"				"500"		// Range within a target can be attacked.
		"ProjectileModel"			"particles/units/heroes/hero_lina/lina_base_attack.vpcf" // Particle system model for projectile.
		"ProjectileSpeed"			"900"		// Speed of projectile.

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"10"		// Experience earn.
		"BountyGoldMin"				"18"		// Gold earned min.
		"BountyGoldMax"				"24"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_SMALL"			// Hull type used for navigation/locomotion.
		"HealthBarOffset"			"130"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"			// Type of locomotion - ground, air
		"MovementSpeed"				"280"		// Speed
		"MovementTurnRate"			"0.9"		// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"260"		// Base health.
		"StatusHealthRegen"			"4"		// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_GOODGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_HERO"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1200"		// Range of vision during day light.
		"VisionNighttimeRange"		"800"		// Range of vision at night time.
	}
	"npc_scorpion_sargatanas_hell_summon"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"	// Class of entity of link to.
		"Model"						"models/items/broodmother/spiderling/ti9_cache_brood_mother_of_thousands_spiderling/ti9_cache_brood_mother_of_thousands_spiderling.vmdl"	// Model.
		"SoundSet"					"Creep_Good_Range"					// Name of sound set.
		"ModelScale"				"0.75"
		"Level"						"1"
		"IsSummoned"				"1"
		"SelectionGroup"			"Spirits"
		"UnitLabel"			"Spirits"
		
		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"ability_firecleave_creep"			// Ability 1.
		"Ability2"					""			// Ability 2.
		"Ability3"					""			// Ability 3.
		"Ability4"					""			// Ability 4.
		"Ability5"					""			// Ability 5.
		"Ability6"					""			// Ability 6 - Extra.
		"Ability7"					""			// Ability 7 - Extra.
		"Ability8"					""			// Ability 8 - Extra.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"2"			// Physical protection.
		"MagicalResistance"				"40"		// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"106"		// Damage range min.
		"AttackDamageMax"			"117"		// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"1.5"			// Speed of attack.
		"AttackAnimationPoint"		"0.2"		// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"800"		// Range within a target can be acquired.
		"AttackRange"				"500"		// Range within a target can be attacked.
		"ProjectileModel"			"particles/units/heroes/hero_lina/lina_base_attack.vpcf" // Particle system model for projectile.
		"ProjectileSpeed"			"900"		// Speed of projectile.

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"10"		// Experience earn.
		"BountyGoldMin"				"18"		// Gold earned min.
		"BountyGoldMax"				"24"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_SMALL"			// Hull type used for navigation/locomotion.
		"HealthBarOffset"			"130"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"			// Type of locomotion - ground, air
		"MovementSpeed"				"280"		// Speed
		"MovementTurnRate"			"0.9"		// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1450"		// Base health.
		"StatusHealthRegen"			"4"		// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_GOODGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_HERO"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1200"		// Range of vision during day light.
		"VisionNighttimeRange"		"800"		// Range of vision at night time.
	}
	"npc_dragon_sargatanas_hell_summon"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"	// Class of entity of link to.
		"Model"						"models/creeps/neutral_creeps/n_creep_black_dragon/n_creep_black_dragon.vmdl"	// Model.
		"SoundSet"					"Creep_Good_Range"					// Name of sound set.
		"ModelScale"				"0.75"
		"Level"						"1"
		"IsSummoned"				"1"
		"SelectionGroup"			"Spirits"
		"UnitLabel"			"Spirits"
		
		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"ability_firecleave_creep"			// Ability 1.
		"Ability2"					""			// Ability 2.
		"Ability3"					""			// Ability 3.
		"Ability4"					""			// Ability 4.
		"Ability5"					""			// Ability 5.
		"Ability6"					""			// Ability 6 - Extra.
		"Ability7"					""			// Ability 7 - Extra.
		"Ability8"					""			// Ability 8 - Extra.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"8"			// Physical protection.
		"MagicalResistance"				"40"		// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"140"		// Damage range min.
		"AttackDamageMax"			"160"		// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"1.5"			// Speed of attack.
		"AttackAnimationPoint"		"0.2"		// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"800"		// Range within a target can be acquired.
		"AttackRange"				"500"		// Range within a target can be attacked.
		"ProjectileModel"			"particles/units/heroes/hero_lina/lina_base_attack.vpcf" // Particle system model for projectile.
		"ProjectileSpeed"			"900"		// Speed of projectile.

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"10"		// Experience earn.
		"BountyGoldMin"				"18"		// Gold earned min.
		"BountyGoldMax"				"24"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_SMALL"			// Hull type used for navigation/locomotion.
		"HealthBarOffset"			"130"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"			// Type of locomotion - ground, air
		"MovementSpeed"				"280"		// Speed
		"MovementTurnRate"			"0.9"		// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"670"		// Base health.
		"StatusHealthRegen"			"4"		// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_GOODGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_HERO"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1200"		// Range of vision during day light.
		"VisionNighttimeRange"		"800"		// Range of vision at night time.
	}
	"npc_kaban_sargatanas_hell_summon"
	{
		// General
		//
		"BaseClass"					"npc_dota_creature"	// Class of entity of link to.
		"Model"						"models/heroes/beastmaster/beastmaster_beast.vmdl"	// Model.
		"SoundSet"					"Creep_Good_Range"					// Name of sound set.
		"ModelScale"				"0.75"
		"Level"						"1"
		"IsSummoned"				"1"
		"SelectionGroup"			"Spirits"
		"UnitLabel"			"Spirits"
		
		// Abilities
		//----------------------------------------------------------------
		
		"Ability1"					"ability_firecleave_creep"			// Ability 1.
		"Ability2"					"ghoul_crazy_look"			// Ability 2.
		"Ability3"					""			// Ability 3.
		"Ability4"					""			// Ability 4.
		"Ability5"					""			// Ability 5.
		"Ability6"					""			// Ability 6 - Extra.
		"Ability7"					""			// Ability 7 - Extra.
		"Ability8"					""			// Ability 8 - Extra.

		// Armor
		//----------------------------------------------------------------
		"ArmorPhysical"				"22"			// Physical protection.
		"MagicalResistance"				"80"		// Magical protection.

		// Attack
		//----------------------------------------------------------------
		"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"			"280"		// Damage range min.
		"AttackDamageMax"			"292"		// Damage range max.
		"AttackDamageType"			"DAMAGE_TYPE_ArmorPhysical"
		"AttackRate"				"1.2"			// Speed of attack.
		"AttackAnimationPoint"		"0.2"		// Normalized time in animation cycle to attack.
		"AttackAcquisitionRange"	"800"		// Range within a target can be acquired.
		"AttackRange"				"700"		// Range within a target can be attacked.
		"ProjectileModel"			"particles/units/heroes/hero_lina/lina_base_attack.vpcf" // Particle system model for projectile.
		"ProjectileSpeed"			"900"		// Speed of projectile.

		// Bounty
		//----------------------------------------------------------------
		"BountyXP"					"10"		// Experience earn.
		"BountyGoldMin"				"18"		// Gold earned min.
		"BountyGoldMax"				"24"		// Gold earned max.

		// Bounds
		//----------------------------------------------------------------
		"BoundsHullName"			"DOTA_HULL_SIZE_SMALL"			// Hull type used for navigation/locomotion.
		"HealthBarOffset"			"130"

		// Movement
		//----------------------------------------------------------------
		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"			// Type of locomotion - ground, air
		"MovementSpeed"				"550"		// Speed
		"MovementTurnRate"			"0.25"		// Turning rate.

		// Status
		//----------------------------------------------------------------
		"StatusHealth"				"1270"		// Base health.
		"StatusHealthRegen"			"14"		// Health regeneration rate.
		"StatusMana"				"0"			// Base mana.
		"StatusManaRegen"			"0"			// Mana regeneration rate.

		// Team
		//----------------------------------------------------------------
		"TeamName"					"DOTA_TEAM_GOODGUYS"			// Team name.
		"CombatClassAttack"			"DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend"			"DOTA_COMBAT_CLASS_DEFEND_HERO"
		"UnitRelationshipClass"		"DOTA_NPC_UNIT_RELATIONSHIP_TYPE_DEFAULT"
		
		// Vision
		//----------------------------------------------------------------
		"VisionDaytimeRange"		"1200"		// Range of vision during day light.
		"VisionNighttimeRange"		"800"		// Range of vision at night time.
	}					
}